local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-CrossArrayMain_group_crossarray_Game",
			UUID = "a23b50c8_1520_4dff_8f76_f68dff9691fe",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "img_bg_Panel-CrossArrayMain_group_crossarray_Game",
					UUID = "779fd133_2e4d_43d7_bf85_afe9bedc82a7",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "True",
					name = "img_bg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "770",
					texturePath = "ui_new/crossarray/img_bg.jpg",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					width = "1136",
					ZOrder = "1",
				},
				{
					controlID = "btn_fanhui_Panel-CrossArrayMain_group_crossarray_Game",
					UUID = "75b85e74_0b7b_4922_95d5_ff705f3a858c",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "56",
					ignoreSize = "True",
					name = "btn_fanhui",
					normal = "ui_new/common/xx_fanhui_btn.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 43,
						PositionY = 612,
						LeftPositon = 2,
						relativeToName = "Panel",
						nType = 3,
					},
					UItype = "Button",
					width = "83",
					ZOrder = "1",
				},
				{
					controlID = "btn_help_Panel-CrossArrayMain_group_crossarray_Game",
					UUID = "17d6d49a_b4a2_4af8_9a3c_6808c71a466f",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "50",
					HitType = 
					{
						nHitType = 1,
						nXpos = -15,
						nYpos = -23,
						nHitWidth = 80,
						nHitHeight = 90
					},
					ignoreSize = "True",
					name = "btn_help",
					normal = "ui_new/common/btn_bangzu.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 923,
						PositionY = 605,
						RightPosition = 12,
						TopPosition = 10,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					UItype = "Button",
					visible = "False",
					width = "50",
					ZOrder = "1",
				},
				{
					controlID = "bg_cengshu_Panel-CrossArrayMain_group_crossarray_Game",
					UUID = "874ed127_2c9e_4c5a_8da9_e720579c6da1",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "54",
					ignoreSize = "False",
					name = "bg_cengshu",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/home/main_tongbi_icon.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 617,
						TopPosition = -4,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 2
					},
					width = "215",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "txt_ceng_bg_cengshu_Panel-CrossArrayMain_group_crossarray_Game",
							UUID = "a95d9cfe_2691_468f_a31f_ab126e3c74bc",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "35",
							ignoreSize = "True",
							name = "txt_ceng",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "Tầng 2",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 43,
								PositionY = 2,
							},
							width = "63",
							ZOrder = "1",
						},
						{
							controlID = "txt_name_bg_cengshu_Panel-CrossArrayMain_group_crossarray_Game",
							UUID = "4260b84a_a0ef_46cb_b022_f94bc4224b2b",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "35",
							ignoreSize = "True",
							name = "txt_name",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "Ngũ Hành",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -36,
								PositionY = 2,
							},
							width = "85",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
					UUID = "dfb96a68_2d26_4cc2_8f45_5684f101a198",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_yun",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "txt_sx_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
							UUID = "9a570629_a433_4c71_8d9e_7421471461ad",
							anchorPoint = "False",
							anchorPointX = "1",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "20",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF000000",
								StrokeSize = 2,
							},
							height = "36",
							ignoreSize = "True",
							name = "txt_sx",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "TextLable",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 740,
								PositionY = 619,
							},
							width = "86",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_effect1_txt_sx_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
									UUID = "c5eac003_299a_41b5_90a6_ff63d76d1eb6",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_56.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_effect1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "LabelBMFont",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 0,
										PositionY = -4,
									},
									width = "100",
									ZOrder = "1",
								},
								{
									controlID = "txt_effect2_txt_sx_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
									UUID = "a184a22e_0ea0_461b_9dbc_125aa770cd5b",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_53.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_effect2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "LabelBMFont",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 0,
										PositionY = -7,
									},
									visible = "False",
									width = "100",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_click_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
							UUID = "957afe9f_1802_4d67_a243_ef6ffff830a1",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "105",
							ignoreSize = "False",
							name = "btn_click",
							sizepercentx = "41",
							sizepercenty = "62",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 178,
								PositionY = 532,
								relativeToName = "Panel",
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "110",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_item_btn_click_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
									UUID = "71e88c13_ccc6_470e_b63f_f510a10c34c8",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "132",
									ignoreSize = "True",
									name = "img_item",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/crossarray/img_yun.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "179",
									ZOrder = "1",
								},
								{
									controlID = "img_close_btn_click_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
									UUID = "df2245de_ef64_4aaa_b738_51c5952377c1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "100",
									ignoreSize = "True",
									name = "img_close",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/crossarray/img_x.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									visible = "False",
									width = "121",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_zhenwei_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
							UUID = "4ac046d3_32ee_41fd_aed3_e0b04ab00b4f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "132",
							ignoreSize = "True",
							name = "btn_zhenwei",
							normal = "ui_new/crossarray/img_zw.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								
							},
							UItype = "Button",
							width = "149",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_touxiang_btn_zhenwei_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
									UUID = "b32c1d6e_df7c_4bfc_a65a_fcaf3b957abf",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "94",
									ignoreSize = "True",
									name = "img_touxiang",
									scaleX = "0.75",
									scaleY = "0.75",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/head/10252.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 1,
										PositionY = -3,
									},
									width = "95",
									ZOrder = "1",
								},
								{
									controlID = "img_zw_btn_zhenwei_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
									UUID = "7f4606ab_8965_45e6_aeb8_fdcce994c812",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "31",
									ignoreSize = "True",
									name = "img_zw",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/crossarray/img_zw2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 6,
										PositionY = -38,
									},
									width = "74",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_hufa_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
							UUID = "220f5f0e_79c1_453d_b27d_96fe8f497064",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "132",
							ignoreSize = "True",
							name = "btn_hufa",
							normal = "ui_new/crossarray/img_boss.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								
							},
							UItype = "Button",
							width = "149",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_touxiang_btn_hufa_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
									UUID = "5589f0e8_1a2a_4302_bf49_6ad1b3925c0b",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "94",
									ignoreSize = "True",
									name = "img_touxiang",
									scaleX = "0.75",
									scaleY = "0.75",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/head/10289.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 2,
									},
									width = "95",
									ZOrder = "1",
								},
								{
									controlID = "img_toumingdi_btn_hufa_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
									UUID = "4872288f_cf22_477b_8a80_8bc92df507d1",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "87",
									ignoreSize = "True",
									name = "img_toumingdi",
									opacity = "200",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/crossarray/img_boss1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 2,
									},
									width = "100",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "txt_sx2_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
							UUID = "fc7c2eda_bb91_4918_aee9_a33238764636",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "20",
							fontStroke = 
							{
								IsStroke = true,
								StrokeColor = "#FF000000",
								StrokeSize = 2,
							},
							height = "36",
							ignoreSize = "True",
							name = "txt_sx2",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "HP tối đa toàn thể",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 135,
								PositionY = 619,
							},
							width = "153",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_effect1_txt_sx2_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
									UUID = "44557c65_f5b0_4c72_9609_0a5a6dd6a6cf",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_56.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_effect1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "LabelBMFont",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 138,
										PositionY = -4,
									},
									width = "100",
									ZOrder = "1",
								},
								{
									controlID = "txt_effect2_txt_sx2_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
									UUID = "6d8a2995_635e_4948_8707_91b75f29b76d",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabelBMFont",
									dstBlendFunc = "771",
									fileNameData = "font/num_53.fnt",
									height = "27",
									ignoreSize = "True",
									name = "txt_effect2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "LabelBMFont",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 133,
										PositionY = -7,
									},
									visible = "False",
									width = "100",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_box_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
							UUID = "503cd6f7_79c7_4f94_b631_aba62cdcc5ee",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "105",
							ignoreSize = "False",
							name = "btn_box",
							sizepercentx = "41",
							sizepercenty = "62",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "110",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_item_btn_box_panel_yun_Panel-CrossArrayMain_group_crossarray_Game",
									UUID = "6db562d0_07a5_4601_91ee_6bd8032b32ad",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "154",
									ignoreSize = "True",
									name = "img_item",
									scaleX = "0.9",
									scaleY = "0.9",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/longmenpo/img_bx.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										
									},
									width = "154",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "btn_cz_Panel-CrossArrayMain_group_crossarray_Game",
					UUID = "309fc6e1_fd1e_4926_b192_6f5e88ffff9d",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "58",
					ignoreSize = "True",
					name = "btn_cz",
					normal = "ui_new/crossarray/btn_cz.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 902,
						PositionY = 58,
						RightPosition = 9,
						BottomPosition = 29,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 9
					},
					UItype = "Button",
					width = "97",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/crossarray/img_bg.jpg",
			"ui_new/common/xx_fanhui_btn.png",
			"ui_new/common/btn_bangzu.png",
			"ui_new/home/main_tongbi_icon.png",
			"ui_new/crossarray/img_yun.png",
			"ui_new/crossarray/img_x.png",
			"ui_new/crossarray/img_zw.png",
			"icon/head/10252.png",
			"ui_new/crossarray/img_zw2.png",
			"ui_new/crossarray/img_boss.png",
			"icon/head/10289.png",
			"ui_new/crossarray/img_boss1.png",
			"ui_new/longmenpo/img_bx.png",
			"ui_new/crossarray/btn_cz.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

