local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-CreatePlayerLayer_group_login_Game",
			UUID = "9479ebbb_ad13_49c4_ae0a_232efd11ebc6",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "bg_Panel-CreatePlayerLayer_group_login_Game",
					UUID = "8c0f345f_92b2_470d_ae66_1751b45aea08",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "True",
					name = "bg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "bg_jpg/cjjs_bj_bg.jpg",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 560,
						PositionY = 355,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "img_role_bg_Panel-CreatePlayerLayer_group_login_Game",
							UUID = "ca8bb0bd_8e48_4ec6_9460_7cae9f77ed5f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "504",
							ignoreSize = "True",
							name = "img_role",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "icon/rolebig/10001.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -209,
								PositionY = -182,
							},
							width = "475",
							ZOrder = "1",
						},
						{
							controlID = "Image_CreatePlayerLayer_1(3)_bg_Panel-CreatePlayerLayer_group_login_Game",
							UUID = "fe13f4cd_b104_4b08_8902_000502738e2f",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "41",
							ignoreSize = "True",
							name = "Image_CreatePlayerLayer_1(3)",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/createplayer/cjjs_jsmc_icon.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -190,
								PositionY = -244,
							},
							width = "429",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "btn_roll_Image_CreatePlayerLayer_1(3)_bg_Panel-CreatePlayerLayer_group_login_Game",
									UUID = "f4a2864e_3502_477e_8c5f_e031001c1796",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "41",
									HitType = 
									{
										nHitType = 1,
										nXpos = -20,
										nYpos = -50,
										nHitWidth = 100,
										nHitHeight = 150
									},
									ignoreSize = "True",
									name = "btn_roll",
									normal = "ui_new/createplayer/cjjs_sj_icon.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 209,
										PositionY = -1,
									},
									UItype = "Button",
									width = "40",
									ZOrder = "1",
								},
								{
									controlID = "playernameInput_Image_CreatePlayerLayer_1(3)_bg_Panel-CreatePlayerLayer_group_login_Game",
									UUID = "1ff44e16_128d_42c5_9a93_375764c0a610",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									classname = "METextField",
									ColorMixing = "#FF000000",
									CursorEnabled = "True",
									dstBlendFunc = "771",
									fontName = "simhei",
									fontSize = "26",
									hAlignment = "0",
									height = "26",
									HitType = 
									{
										nHitType = 1,
										nXpos = -100,
										nYpos = -50,
										nHitWidth = 320,
										nHitHeight = 150
									},
									ignoreSize = "True",
									KeyBoradType = "0",
									maxLengthEnable = "True;maxLength:16",
									name = "playernameInput",
									passwordEnable = "False",
									placeHolder = "Enter a Name",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 4,
										PositionY = 1,
									},
									vAlignment = "0",
									width = "156",
									ZOrder = "9",
								},
							},
						},
					},
				},
				{
					controlID = "createOkBtn_Panel-CreatePlayerLayer_group_login_Game",
					UUID = "5c83bf50_c07d_4593_9957_cfa1c5b7f011",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "70",
					ignoreSize = "True",
					name = "createOkBtn",
					normal = "ui_new/createplayer/cjjs_qd_btn.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 1042,
						PositionY = 35,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 9
					},
					UItype = "Button",
					width = "156",
					ZOrder = "1",
				},
				{
					controlID = "Image_CreatePlayerLayer_1_Panel-CreatePlayerLayer_group_login_Game",
					UUID = "720d04eb_3ffa_40f0_9afe_bd68546c69ef",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "55",
					ignoreSize = "True",
					name = "Image_CreatePlayerLayer_1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/cjjs_cjjs_title.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 116,
						PositionY = 678,
						TopPosition = 5,
						relativeToName = "Panel",
						nType = 3,
					},
					width = "233",
					ZOrder = "1",
				},
				{
					controlID = "Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
					UUID = "70b5d5d0_7ae1_4d8c_83e2_9f5be03eca49",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "True",
					name = "Image_CreatePlayerLayer_1(4)",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/cjjs_smd_icon.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 963,
						PositionY = 387,
						RightPosition = 90,
						BottomPosition = 67,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 9
					},
					width = "134",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "btn_role_1_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
							UUID = "f183356f_0c23_41b0_9d03_3e53e34662bd",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "25",
							ignoreSize = "True",
							name = "btn_role_1",
							normal = "ui_new/createplayer/cjjs_txd_off_btn.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -50,
								PositionY = 186,
							},
							UItype = "Button",
							width = "60",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_icon_1_btn_role_1_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
									UUID = "a959ea6b_7bf1_48f0_8290_9d2dc7f7e6dd",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "94",
									ignoreSize = "True",
									name = "img_icon_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/head/10002.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 6,
									},
									width = "95",
									ZOrder = "1",
								},
								{
									controlID = "Image_CreatePlayerLayer_1_btn_role_1_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
									UUID = "883a77e8_1f76_4529_b308_d2bc51e835c7",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_CreatePlayerLayer_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/createplayer/cjjs_scgj_word.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 12,
										PositionY = -65,
									},
									width = "64",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "img_choice_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
							UUID = "f42b87aa_c324_41ef_af2c_7ee42807394e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "img_choice",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/createplayer/cjjs_txd_on_btn.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -50,
								PositionY = 186,
							},
							width = "64",
							ZOrder = "10",
						},
						{
							controlID = "btn_role_2_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
							UUID = "128a70a1_5a71_449d_8d85_52cf5f443732",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "25",
							ignoreSize = "True",
							name = "btn_role_2",
							normal = "ui_new/createplayer/cjjs_txd_off_btn.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 111,
								PositionY = 118,
							},
							UItype = "Button",
							width = "60",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_icon_2_btn_role_2_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
									UUID = "a033ee9f_660c_40b4_b9f6_c6fbc73b5d5a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "94",
									ignoreSize = "True",
									name = "img_icon_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/head/10002.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 6,
									},
									width = "95",
									ZOrder = "1",
								},
								{
									controlID = "Image_CreatePlayerLayer_2_btn_role_2_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
									UUID = "d0bb0d9e_b443_4994_8a02_86dbee77c9cf",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_CreatePlayerLayer_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/createplayer/cjjs_sczl_word.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 12,
										PositionY = -65,
									},
									width = "64",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_role_3_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
							UUID = "4be04a8b_e574_4162_b003_c67d20fa7168",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "25",
							ignoreSize = "True",
							name = "btn_role_3",
							normal = "ui_new/createplayer/cjjs_txd_off_btn.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 110,
								PositionY = -50,
							},
							UItype = "Button",
							width = "60",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_icon_3_btn_role_3_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
									UUID = "bdbf8ba5_e08c_4a25_b479_2720801c2cc0",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "94",
									ignoreSize = "True",
									name = "img_icon_3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/head/10002.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 6,
									},
									width = "95",
									ZOrder = "1",
								},
								{
									controlID = "Image_CreatePlayerLayer_3_btn_role_3_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
									UUID = "b7949a00_ddac_4302_9a14_86e759d090d6",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_CreatePlayerLayer_3",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/createplayer/cjjs_sckz_word.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 2,
										PositionY = -65,
									},
									width = "64",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_role_4_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
							UUID = "54f212da_8786_4cec_9a3a_c66444465b34",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "25",
							ignoreSize = "True",
							name = "btn_role_4",
							normal = "ui_new/createplayer/cjjs_txd_off_btn.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -17,
								PositionY = -141,
							},
							UItype = "Button",
							width = "60",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_icon_4_btn_role_4_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
									UUID = "be5418a2_7262_4a48_b7ac_05e6c041a450",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "94",
									ignoreSize = "True",
									name = "img_icon_4",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "icon/head/10002.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 6,
									},
									width = "95",
									ZOrder = "1",
								},
								{
									controlID = "Image_CreatePlayerLayer_4_btn_role_4_Image_CreatePlayerLayer_1(4)_Panel-CreatePlayerLayer_group_login_Game",
									UUID = "ea5acf18_c29f_4bca_98ff_74c49f04f9d8",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_CreatePlayerLayer_4",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/createplayer/cjjs_scfy_word.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 2,
										PositionY = -65,
									},
									width = "64",
									ZOrder = "1",
								},
							},
						},
					},
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"bg_jpg/cjjs_bj_bg.jpg",
			"icon/rolebig/10001.png",
			"ui_new/createplayer/cjjs_jsmc_icon.png",
			"ui_new/createplayer/cjjs_sj_icon.png",
			"ui_new/createplayer/cjjs_qd_btn.png",
			"ui_new/createplayer/cjjs_cjjs_title.png",
			"ui_new/createplayer/cjjs_smd_icon.png",
			"ui_new/createplayer/cjjs_txd_off_btn.png",
			"icon/head/10002.png",
			"ui_new/createplayer/cjjs_scgj_word.png",
			"ui_new/createplayer/cjjs_txd_on_btn.png",
			"ui_new/createplayer/cjjs_sczl_word.png",
			"ui_new/createplayer/cjjs_sckz_word.png",
			"ui_new/createplayer/cjjs_scfy_word.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

