local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-CreatePlayerNew_group_login_Game",
			UUID = "a874bc91_14cc_4572_8b77_303bdb5c9e0c",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "710",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "1120",
			ZOrder = "1",
			components = 
			{
				
				{
					controlID = "bg_Panel-CreatePlayerNew_group_login_Game",
					UUID = "ca15a88d_ef11_40a2_81b1_740c6c54c455",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "True",
					name = "bg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "770",
					texturePath = "bg_jpg/cjjs_bj_bg.jpg",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 320,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					width = "1136",
					ZOrder = "1",
				},
				{
					controlID = "img_house_bg_Panel-CreatePlayerNew_group_login_Game",
					UUID = "e136ea41_47a5_4943_800c_11ab9483c273",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "64",
					ignoreSize = "True",
					name = "img_house_bg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 320,
						RightPosition = 448,
						TopPosition = 288,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					width = "64",
					ZOrder = "1",
				},
				{
					controlID = "img_wuyan_Panel-CreatePlayerNew_group_login_Game",
					UUID = "459d8d06_7230_499d_b3ca_fc6279b7e145",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "513",
					ignoreSize = "True",
					name = "img_wuyan",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/bg_wuyan.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 450,
						PositionY = 256,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 4,
						nAlign = 7
					},
					width = "901",
					ZOrder = "1",
				},
				{
					controlID = "biaoti_Panel-CreatePlayerNew_group_login_Game",
					UUID = "14175216_ce22_404e_a0db_e8ca310c8510",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "55",
					ignoreSize = "True",
					name = "biaoti",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/cjjs_cjjs_title.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 116,
						PositionY = 599,
						TopPosition = 13,
						relativeToName = "Panel",
						nType = 3,
					},
					width = "233",
					ZOrder = "1",
				},
				{
					controlID = "anim_panel_Panel-CreatePlayerNew_group_login_Game",
					UUID = "126728a0_9145_46ae_b08e_cf69df1bea03",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "400",
					ignoreSize = "False",
					name = "anim_panel",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 204,
						PositionY = 163,
						LeftPositon = 204,
						TopPosition = 77,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 1,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "400",
					ZOrder = "1",
				},
				{
					controlID = "panel_flower_Panel-CreatePlayerNew_group_login_Game",
					UUID = "6da8a21c_66e8_4382_9311_ecc837ee8777",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "400",
					ignoreSize = "False",
					name = "panel_flower",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionY = -69,
						TopPosition = 309,
						relativeToName = "Panel",
						nType = 3,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "400",
					ZOrder = "1",
				},
				{
					controlID = "role_big_Panel-CreatePlayerNew_group_login_Game",
					UUID = "2f237b17_79ec_4e6b_919b_962db85c9e13",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "450",
					ignoreSize = "True",
					name = "role_big",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/role_1.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 220,
						PositionY = 342,
						LeftPositon = -40,
						TopPosition = 73,
						relativeToName = "Panel",
						nType = 3,
					},
					width = "520",
					ZOrder = "1",
				},
				{
					controlID = "bg_zhiye_Panel-CreatePlayerNew_group_login_Game",
					UUID = "e79135b0_01f1_4c52_ba9c_685be9c9007d",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "True",
					name = "bg_zhiye",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/cjjs_smd_icon.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 776,
						PositionY = 320,
						RightPosition = 117,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					width = "134",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Button_CreatePlayerNew_1_bg_zhiye_Panel-CreatePlayerNew_group_login_Game",
							UUID = "621e68e3_354e_4b13_b3b2_fe8f281e3492",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "156",
							HitType = 
							{
								nHitType = 1,
								nXpos = 0,
								nYpos = 9,
								nHitWidth = 212,
								nHitHeight = 126
							},
							ignoreSize = "True",
							name = "Button_CreatePlayerNew_1",
							normal = "ui_new/createplayer/g1b.png",
							pressed = "ui_new/createplayer/g1.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionY = 156,
							},
							UItype = "Button",
							width = "177",
							ZOrder = "1",
						},
						{
							controlID = "Button_CreatePlayerNew_2_bg_zhiye_Panel-CreatePlayerNew_group_login_Game",
							UUID = "cdb04cd2_f94e_4cc5_aa08_1d924e91e3ab",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "154",
							ignoreSize = "True",
							name = "Button_CreatePlayerNew_2",
							normal = "ui_new/createplayer/g3b.png",
							pressed = "ui_new/createplayer/g3.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -79,
								PositionY = 31,
							},
							UItype = "Button",
							width = "188",
							ZOrder = "1",
						},
						{
							controlID = "Button_CreatePlayerNew_3_bg_zhiye_Panel-CreatePlayerNew_group_login_Game",
							UUID = "5b838eb1_57ed_4b1b_a7a4_687fb0a55bee",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "152",
							ignoreSize = "True",
							name = "Button_CreatePlayerNew_3",
							normal = "ui_new/createplayer/g4b.png",
							pressed = "ui_new/createplayer/g4.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -12,
								PositionY = -102,
							},
							UItype = "Button",
							width = "165",
							ZOrder = "1",
						},
						{
							controlID = "Button_CreatePlayerNew_4_bg_zhiye_Panel-CreatePlayerNew_group_login_Game",
							UUID = "7aec1cae_1d94_472c_bc5c_cc84afc3ddcb",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "151",
							ignoreSize = "True",
							name = "Button_CreatePlayerNew_4",
							normal = "ui_new/createplayer/g2b.png",
							pressed = "ui_new/createplayer/g2.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 89,
								PositionY = 25,
							},
							UItype = "Button",
							width = "185",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "bg_shuoming_Panel-CreatePlayerNew_group_login_Game",
					UUID = "a1be14a8_ee01_4a76_93a8_1547802117ec",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "102",
					ignoreSize = "True",
					name = "bg_shuoming",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/bg_txt.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 253,
						PositionY = 141,
						LeftPositon = 131,
						TopPosition = 448,
						relativeToName = "Panel",
						nType = 3,
					},
					width = "245",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Img_zhiye_bg_shuoming_Panel-CreatePlayerNew_group_login_Game",
							UUID = "578977c1_249c_4191_b0bf_edac73c5e350",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "113",
							ignoreSize = "True",
							name = "Img_zhiye",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/common/img_role_type1.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -143,
								PositionY = 8,
							},
							width = "44",
							ZOrder = "1",
						},
						{
							controlID = "TextDesc1_bg_shuoming_Panel-CreatePlayerNew_group_login_Game",
							UUID = "f2cf72d4_b957_4019_a412_8eb804d547bf",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "METextArea",
							dstBlendFunc = "771",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							hAlignment = "0",
							height = "0",
							ignoreSize = "False",
							name = "TextDesc1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "Jian Mo Descendant",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -115,
								PositionY = 34,
							},
							vAlignment = "0",
							width = "250",
							ZOrder = "1",
						},
						{
							controlID = "TextDesc2_bg_shuoming_Panel-CreatePlayerNew_group_login_Game",
							UUID = "3cfe7576_c4d9_4e90_8718_eda98ee98bd2",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0.5",
							classname = "METextArea",
							dstBlendFunc = "771",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "22",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							hAlignment = "0",
							height = "0",
							ignoreSize = "False",
							name = "TextDesc2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "Super solid Black Iron Sword",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = -115,
								PositionY = -9,
							},
							vAlignment = "0",
							width = "250",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Btn_star_Panel-CreatePlayerNew_group_login_Game",
					UUID = "699554bd_dac7_4f7b_bdd1_240f6470cfe1",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "70",
					ignoreSize = "True",
					name = "Btn_star",
					normal = "ui_new/createplayer/cjjs_qd_btn.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 776,
						PositionY = 60,
						RightPosition = 106,
						TopPosition = 545,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					UItype = "Button",
					width = "156",
					ZOrder = "1",
				},
				{
					controlID = "bg_name_Panel-CreatePlayerNew_group_login_Game",
					UUID = "184353c1_42c5_4b3b_a0eb_d433633c9a4a",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "41",
					ignoreSize = "True",
					name = "bg_name",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/createplayer/cjjs_jsmc_icon.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 480,
						PositionY = 59,
						TopPosition = 560,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 2
					},
					width = "429",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Btn_rename_bg_name_Panel-CreatePlayerNew_group_login_Game",
							UUID = "9f643624_7043_4ee6_8bf6_f9cea084ba33",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "41",
							HitType = 
							{
								nHitType = 1,
								nXpos = -10,
								nYpos = -17,
								nHitWidth = 80,
								nHitHeight = 80
							},
							ignoreSize = "True",
							name = "Btn_rename",
							normal = "ui_new/createplayer/cjjs_sj_icon.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 141,
							},
							UItype = "Button",
							width = "40",
							ZOrder = "1",
						},
						{
							controlID = "playernameInput_bg_name_Panel-CreatePlayerNew_group_login_Game",
							UUID = "67c22598_dde7_43e6_aac9_ae35a4e0f2b3",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "METextField",
							CursorEnabled = "True",
							dstBlendFunc = "771",
							fontName = "simhei",
							fontSize = "26",
							hAlignment = "0",
							height = "29",
							HitType = 
							{
								nHitType = 1,
								nXpos = -95,
								nYpos = -35,
								nHitWidth = 190,
								nHitHeight = 72
							},
							ignoreSize = "True",
							KeyBoradType = "0",
							maxLengthEnable = "True;maxLength:16",
							name = "playernameInput",
							outlineColor = "#FF000000",
							outlineSize = "1",
							passwordEnable = "False",
							placeHolder = "Enter a Name",
							shadowColor = "#FF000000",
							shadowHeight = "0",
							shadowWidth = "0",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 4,
								PositionY = 1,
							},
							useOutline = "False",
							useShadow = "False",
							vAlignment = "0",
							width = "151",
							ZOrder = "9",
						},
					},
				},
				{
					controlID = "btn_tianxie_Panel-CreatePlayerNew_group_login_Game",
					UUID = "a8f13024_3d99_4c86_94b6_6d69b90b9845",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "50",
					ignoreSize = "True",
					name = "btn_tianxie",
					normal = "ui_new/qiyu/family/btn_tianxie.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 137,
						PositionY = 58,
						LeftPositon = 57,
						TopPosition = 557,
						relativeToName = "Panel",
						nType = 3,
					},
					UItype = "Button",
					width = "161",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"bg_jpg/cjjs_bj_bg.jpg",
			"ui_new/createplayer/bg_wuyan.png",
			"ui_new/createplayer/cjjs_cjjs_title.png",
			"ui_new/createplayer/role_1.png",
			"ui_new/createplayer/cjjs_smd_icon.png",
			"ui_new/createplayer/g1.png",
			"ui_new/createplayer/g1b.png",
			"ui_new/createplayer/g3.png",
			"ui_new/createplayer/g3b.png",
			"ui_new/createplayer/g4.png",
			"ui_new/createplayer/g4b.png",
			"ui_new/createplayer/g2.png",
			"ui_new/createplayer/g2b.png",
			"ui_new/createplayer/bg_txt.png",
			"ui_new/common/img_role_type1.png",
			"ui_new/createplayer/cjjs_qd_btn.png",
			"ui_new/createplayer/cjjs_jsmc_icon.png",
			"ui_new/createplayer/cjjs_sj_icon.png",
			"ui_new/qiyu/family/btn_tianxie.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

