local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-LoginLayer_group_login_Game",
			UUID = "00384d8a_4a60_4327_bdc2_88d4b1d59ce0",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "2",
			components = 
			{
				
				{
					controlID = "Panel_1_Panel-LoginLayer_group_login_Game",
					UUID = "1771b879_4589_42cd_b15f_d2777642986b",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 80,
						PositionY = 35,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "panel_ef1_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "42a8f866_4d0d_4339_b0b3_ae25fe09a364",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "panel_ef1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "960",
							ZOrder = "1",
						},
						{
							controlID = "panel_ef2_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "59254087_ea48_4ac9_b4ef_f100a08e8ad3",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "panel_ef2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "960",
							ZOrder = "1",
						},
						{
							controlID = "panel_ef3_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "82893216_c278_432d_8295_fc310bbb96c3",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "panel_ef3",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "960",
							ZOrder = "1",
						},
						{
							controlID = "bg_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "b0f8f0e2_dfc6_4f10_a264_cfff22df276c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "True",
							name = "bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							texturePath = "ui_new/login/img_bg.jpg",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 320,
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							visible = "False",
							width = "1136",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "Image_LoginLayer_2_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "d18c100b_afd4_4d27_add8_4c8c675715c2",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_LoginLayer_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/bg_2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -130,
										PositionY = -97,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "Image_LoginLayer_1_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "0ef70599_0797_4915_a721_f68f3fc9eed6",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_LoginLayer_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/bg_1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -163,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "panel_touch_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "63d26990_4186_4271_9eca_3d2e6423fe2e",
							anchorPoint = "False",
							anchorPointX = "0",
							anchorPointY = "0",
							backGroundScale9Enable = "False",
							bgColorOpacity = "50",
							bIsOpenClipping = "False",
							classname = "MEPanel",
							colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
							DesignHeight = "640",
							DesignType = "0",
							DesignWidth = "960",
							dstBlendFunc = "771",
							height = "640",
							ignoreSize = "False",
							name = "panel_touch",
							sizepercentx = "100",
							sizepercenty = "100",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = -88,
								relativeToName = "Panel",
							},
							uipanelviewmodel = 
							{
								Layout="Absolute",
								nType = "0"
							},
							width = "1136",
							ZOrder = "1",
						},
						{
							controlID = "img_input_bg_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "79635a46_b4ae_4e25_b656_fd3048015f54",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "-1.3",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "46",
							ignoreSize = "True",
							name = "img_input_bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/bg_shuru.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 490,
								PositionY = 123,
							},
							width = "476",
							ZOrder = "3",
							components = 
							{
								
								{
									controlID = "input_name_img_input_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "3a3c8e55_d139_4967_a918_093ccc721d30",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "METextField",
									ColorMixing = "#FF000000",
									CursorEnabled = "True",
									dstBlendFunc = "771",
									fontName = "simhei",
									fontSize = "30",
									hAlignment = "0",
									height = "30",
									HitType = 
									{
										nHitType = 1,
										nXpos = -50,
										nYpos = -10,
										nHitWidth = 340,
										nHitHeight = 50
									},
									ignoreSize = "True",
									KeyBoradType = "0",
									maxLengthEnable = "True;maxLength:20",
									name = "input_name",
									passwordEnable = "False",
									placeHolder = "Nhập TK, Tự Động ĐK",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -130,
										PositionY = 83
									},
									vAlignment = "0",
									visible = "False",
									width = "240",
									ZOrder = "9",
								},{
									controlID = "input_name_img_input_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "b88f435c_f2b5_43e1_acb7_bb8bfb2c7256",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									classname = "METextField",
									ColorMixing = "#FF000000",
									CursorEnabled = "True",
									dstBlendFunc = "771",
									fontName = "simhei",
									fontSize = "30",
									hAlignment = "0",
									height = "30",
									HitType = 
									{
										nHitType = 1,
										nXpos = -50,
										nYpos = -10,
										nHitWidth = 340,
										nHitHeight = 50
									},
									ignoreSize = "True",
									KeyBoradType = "0",
									maxLengthEnable = "True;maxLength:20",
									name = "input_pwd",
									outlineColor = "#FF000000",
									outlineSize = "1",
									passwordEnable = "True",
									passwordEnable = "False",
									placeHolder = "Nhập Mật Khẩu",
									shadowColor = "#FF000000",
									shadowHeight = "0",
									shadowWidth = "0",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -130,
									},
									useOutline = "False",
									useShadow = "False",
									vAlignment = "0",
									width = "240",
									ZOrder = "9",
								},
								{
									controlID = "btn_selectAcount_img_input_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "14f212f8_62e8_4408_99b3_703087181388",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "56",
									HitType = 
									{
										nHitType = 1,
										nXpos = -450,
										nYpos = -10,
										nHitWidth = 630,
										nHitHeight = 80
									},
									ignoreSize = "True",
									name = "btn_selectAcount",
									normal = "ui_new/login/zh_qh.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 251,
									},
									UItype = "Button",
									visible = "False",
									width = "124",
									ZOrder = "7",
								},
								{
									controlID = "lb_name_img_input_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "1886dd1d_d5bd_40c5_9b35_28f2ba249254",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FF000000",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "30",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "False",
									name = "lb_name",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "Please log in account",
									touchAble = "True",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -130,
										PositionY = -1,
										LeftPositon = 275,
										TopPosition = 491,
										relativeToName = "Panel",
									},
									visible = "False",
									width = "300",
									ZOrder = "8",
								},
								{
									controlID = "Img_zh_img_input_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "b5775934_89f5_4a56_b9f2_3f34ad4ef1ea",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "36",
									ignoreSize = "True",
									name = "Img_zh",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/img_zh.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -205,
										PositionY = 83,
									},
									width = "70",
									ZOrder = "1",
								},{
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "-1.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "40",
									ignoreSize = "True",
									name = "Img_shuru",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/bg_shuru.png",--
									touchAble = "False",
									UILayoutViewModel = 
									{
									    PositionX = 0,
										PositionY = -75,
									},
									width = "70",
									ZOrder = "1",
								},{
									controlID = "Img_zh_img_input_bg_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "b5775934_89f5_4a56_b9f2_3f34ad4ef1ea",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "36",
									ignoreSize = "True",
									name = "Img_zh",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/img_zh_mk.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -205,
										PositionY = 15,
									},
									width = "70",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "img_account_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "72c65cd2_e7cb_4ac6_a0c7_21e9c7109ba9",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "46",
							ignoreSize = "True",
							name = "img_account",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/bg_shuru.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 490,
								PositionY = 123,
								LeftPositon = 270,
								TopPosition = 113,
								relativeToName = "Panel",
							},
							visible = "False",
							width = "476",
							ZOrder = "3",
							components = 
							{
								
								{
									controlID = "txt_area_img_account_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "22630ee8_6609_4684_85bd_52f63c3a7e43",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FF000000",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "30",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "30",
									ignoreSize = "False",
									name = "txt_area",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									text = "109区  天龙八部",
									touchAble = "True",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = -128,
										LeftPositon = 275,
										TopPosition = 491,
										relativeToName = "Panel",
									},
									width = "300",
									ZOrder = "8",
								},
								{
									controlID = "btn_selectServer_img_account_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "0c977ab1_d88c_4daf_b189_ce8f83436a79",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "18",
									HitType = 
									{
										nHitType = 1,
										nXpos = -477,
										nYpos = -10,
										nHitWidth = 630,
										nHitHeight = 80
									},
									ignoreSize = "True",
									name = "btn_selectServer",
									normal = "ui_new/login/zh_hq.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 250,
										PositionY = -2,
										LeftPositon = 579,
										TopPosition = 483,
										relativeToName = "Panel",
									},
									UItype = "Button",
									width = "95",
									ZOrder = "7",
								},
								{
									controlID = "Img_xq_img_account_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "931b52a5_97fd_47d1_9386_cbd6bad26508",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "36",
									ignoreSize = "True",
									name = "Img_xq",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/img_xq.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -175,
									},
									width = "70",
									ZOrder = "1",
								},
							},
						},
						{
							controlID = "btn_register_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "72eb49e0_6ece_42e5_87cd_39032e477bef",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEButton",
							ClickHighLightEnabled = "True",
							dstBlendFunc = "771",
							flipX = "False",
							flipY = "False",
							height = "25",
							ignoreSize = "True",
							name = "btn_register",
							normal = "ui_new/login/zh_zc.png",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "True",
							UILayoutViewModel = 
							{
								PositionX = 278,
								PositionY = 62,
							},
							UItype = "Button",
							visible = "False",
							width = "60",
							ZOrder = "5",
						},
						{
							controlID = "img_dengru_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "f9b18841_542a_4a6b_81d7_e4e974fda6b2",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "35",
							ignoreSize = "True",
							name = "img_dengru",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/xf_dianji.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 54,
								LeftPositon = 254,
								TopPosition = 553,
								relativeToName = "Panel",
							},
							width = "445",
							ZOrder = "1",
						},
						{
							controlID = "img_gonggaodi_Panel_1_Panel-LoginLayer_group_login_Game",
							UUID = "be8299ba_9d77_4ac6_a41c_92a48cfc6479",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "574",
							ignoreSize = "False",
							name = "img_gonggaodi",
							scaleX = "0.9",
							scaleY = "0.9",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/xf_gonggao.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 320,
							},
							visible = "False",
							width = "798",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "img_gonggao_img_gonggaodi_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "c883ff91_97e8_4d92_9339_527273c12367",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "24",
									ignoreSize = "True",
									name = "img_gonggao",
									scaleX = "0.9",
									scaleY = "0.9",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/xf_gonggao2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = 245,
									},
									visible = "False",
									width = "153",
									ZOrder = "1",
								},
								{
									controlID = "Button_Gonggao_1_img_gonggaodi_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "06606a97_d4a8_4139_8690_ba89ae2ce159",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "70",
									ignoreSize = "True",
									name = "Button_Gonggao_1",
									normal = "ui_new/login/xf_closeicon.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionY = -233,
									},
									UItype = "Button",
									width = "156",
									ZOrder = "1",
								},
								{
									controlID = "bg_title_img_gonggaodi_Panel_1_Panel-LoginLayer_group_login_Game",
									UUID = "63f4810b_e3c8_425c_bb4d_f0abaeb673d8",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "160",
									ignoreSize = "True",
									name = "bg_title",
									scaleX = "1.02",
									scaleY = "1.02",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/bg_gonggao.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
										PositionY = 231,
									},
									width = "826",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "btn_login_Panel-LoginLayer_group_login_Game",
					UUID = "01903cdf_c571_426d_8617_046bd7aaa64e",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "57",
					ignoreSize = "True",
					name = "btn_login",
					normal = "ui_new/login/zh_jr.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 897,
						PositionY = 28,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 9
					},
					UItype = "Button",
					visible = "False",
					width = "445",
					ZOrder = "4",
				},
				{
					controlID = "panel_close_Panel-LoginLayer_group_login_Game",
					UUID = "e89199bc_d205_4030_a3ad_a05e5557eefa",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "100",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_close",
					PanelRelativeSizeModel = 
					{
						PanelRelativeEnable = true,
					},
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionY = 70,
						relativeToName = "Panel",
						nType = 3,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					visible = "False",
					width = "960",
					ZOrder = "5",
				},
				{
					controlID = "img_title_Panel-LoginLayer_group_login_Game",
					UUID = "e7c3dbb3_6319_43f2_80a6_eed8b854ff76",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "149",
					ignoreSize = "True",
					name = "img_title",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/logo.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 949,
						PositionY = 632,
						RightPosition = 15,
						TopPosition = 3,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					width = "311",
					ZOrder = "1",
				},
				{
					controlID = "img_notice_Panel-LoginLayer_group_login_Game",
					UUID = "ba66584b_6f9d_4264_8958_1c5115d213c4",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "24",
					ignoreSize = "True",
					name = "img_notice",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/img_zg.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 560,
						PositionY = 12,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 8
					},
					visible = "False",
					width = "846",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/login/img_bg.jpg",
			"ui_new/login/bg_2.png",
			"ui_new/login/bg_1.png",
			"ui_new/login/bg_shuru.png",
			"ui_new/login/zh_qh.png",
			"ui_new/login/img_zh.png",
			"ui_new/login/zh_hq.png",
			"ui_new/login/img_xq.png",
			"ui_new/login/zh_zc.png",
			"ui_new/login/xf_dianji.png",
			"ui_new/login/xf_gonggao.png",
			"ui_new/login/xf_gonggao2.png",
			"ui_new/login/xf_closeicon.png",
			"ui_new/login/bg_gonggao.png",
			"ui_new/login/zh_jr.png",
			"ui_new/login/logo.png",
			"ui_new/login/img_zg.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

