local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-LoginNoticePage_group_login_Game",
			UUID = "1ce79da1_b4dc_4479_9f64_4dbc2ecaedfb",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "2",
			components = 
			{
				
				{
					controlID = "panel_ef1_Panel-LoginNoticePage_group_login_Game",
					UUID = "7a5a831d_86f9_4dd5_ab8c_64f0934c2a0c",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_ef1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
				},
				{
					controlID = "panel_ef2_Panel-LoginNoticePage_group_login_Game",
					UUID = "5c5f24ce_f9ca_421d_9c81_8d6696d32a21",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_ef2",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
				},
				{
					controlID = "panel_ef3_Panel-LoginNoticePage_group_login_Game",
					UUID = "ea139dec_1da3_462e_a517_cf852b898d43",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_ef3",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
				},
				{
					controlID = "Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
					UUID = "9675e4ff_6357_4aea_b991_832bcae93104",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "50",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "Panel_LoginNoticePage_1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "False",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
							UUID = "88035161_af13_441d_a71f_6c5c3c91c777",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "bg",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = 480,
								PositionY = 320,
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 5
							},
							width = "64",
							ZOrder = "3",
							components = 
							{
								
								{
									controlID = "Image_LoginLayer_1_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "b22a9ff6_dc64_4468_a8ca_ce3b72628b76",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_LoginLayer_1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/bg_1.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -1,
										PositionY = -164,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "Image_LoginLayer_2_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "04f89bb8_050d_4f3b_86df_5fc8a497ff41",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "64",
									ignoreSize = "True",
									name = "Image_LoginLayer_2",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/bg_2.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = -130,
										PositionY = -97,
									},
									visible = "False",
									width = "64",
									ZOrder = "1",
								},
								{
									controlID = "img_account_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "f642322d_7c49_4f9e_86e6_0ae711d79501",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "57",
									ignoreSize = "True",
									name = "img_account",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/zh_xuanqu.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionY = -175,
										LeftPositon = 270,
										TopPosition = 113,
										relativeToName = "Panel",
									},
									width = "374",
									ZOrder = "3",
									components = 
									{
										
										{
											controlID = "txt_area_img_account_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
											UUID = "79bd3383_1e76_47ad_8752_2db6a15bd6f0",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "20",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "False",
											name = "txt_area",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "109区  天龙八部",
											touchAble = "True",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -139,
												PositionY = 3,
												LeftPositon = 275,
												TopPosition = 491,
												relativeToName = "Panel",
											},
											width = "0",
											ZOrder = "8",
										},
										{
											controlID = "btn_selectServer_img_account_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
											UUID = "b1668f6d_7ed9_46c8_b085_08e1c2638387",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "18",
											HitType = 
											{
												nHitType = 1,
												nXpos = -306,
												nYpos = -16,
												nHitWidth = 496,
												nHitHeight = 80
											},
											ignoreSize = "True",
											name = "btn_selectServer",
											normal = "ui_new/login/zh_hq.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 91,
												PositionY = 4,
												LeftPositon = 579,
												TopPosition = 483,
												relativeToName = "Panel",
											},
											UItype = "Button",
											width = "95",
											ZOrder = "7",
										},
									},
								},
								{
									controlID = "btn_register_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "d9653603_4a58_42a4_9126_aa17314259fb",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "25",
									ignoreSize = "True",
									name = "btn_register",
									normal = "ui_new/login/zh_zc.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = 2,
										PositionY = -312,
									},
									UItype = "Button",
									visible = "False",
									width = "60",
									ZOrder = "5",
								},
								{
									controlID = "img_input_bg_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "ec17d716_4f12_441f_b51d_ae3478a73dae",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEImage",
									dstBlendFunc = "771",
									height = "66",
									ignoreSize = "True",
									name = "img_input_bg",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									texturePath = "ui_new/login/zh_zhanghao.png",
									touchAble = "False",
									UILayoutViewModel = 
									{
										PositionX = 1,
										PositionY = -222,
									},
									visible = "False",
									width = "880",
									ZOrder = "3",
									components = 
									{
										
										{
											controlID = "input_name_img_input_bg_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
											UUID = "34ad086e_b16c_435f_9006_3654126b42b6",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "METextField",
											ColorMixing = "#FF000000",
											CursorEnabled = "True",
											dstBlendFunc = "771",
											fontName = "simhei",
											fontSize = "30",
											hAlignment = "0",
											height = "30",
											HitType = 
											{
												nHitType = 1,
												nXpos = -50,
												nYpos = -10,
												nHitWidth = 340,
												nHitHeight = 50
											},
											ignoreSize = "True",
											KeyBoradType = "0",
											maxLengthEnable = "True;maxLength:20",
											name = "input_name",
											passwordEnable = "False",
											placeHolder = "Enter account ID",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = -196,
											},
											vAlignment = "0",
											width = "240",
											ZOrder = "9",
										},
										{
											controlID = "btn_selectAcount_img_input_bg_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
											UUID = "5b11e1a2_ab1b_4f4a_8ee2_cd29a4d5048d",
											anchorPoint = "False",
											anchorPointX = "0.5",
											anchorPointY = "0.5",
											backGroundScale9Enable = "False",
											classname = "MEButton",
											ClickHighLightEnabled = "True",
											dstBlendFunc = "771",
											flipX = "False",
											flipY = "False",
											height = "56",
											HitType = 
											{
												nHitType = 1,
												nXpos = -450,
												nYpos = -10,
												nHitWidth = 630,
												nHitHeight = 80
											},
											ignoreSize = "True",
											name = "btn_selectAcount",
											normal = "ui_new/login/zh_qh.png",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											touchAble = "True",
											UILayoutViewModel = 
											{
												PositionX = 156,
												PositionY = 3,
											},
											UItype = "Button",
											width = "124",
											ZOrder = "7",
										},
										{
											controlID = "lb_name_img_input_bg_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
											UUID = "fcaa864f_bafd_48be_914b_13ac5efcf315",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "0.5",
											classname = "MELabel",
											ColorMixing = "#FF000000",
											compPath = "luacomponents.common.MEIconLabel",
											dstBlendFunc = "771",
											FontColor = "#FFFFFFFF",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "30",
											fontStroke = 
											{
												IsStroke = false,
												StrokeColor = "#FFE6E6E6",
												StrokeSize = 1,
											},
											height = "30",
											ignoreSize = "False",
											name = "lb_name",
											nTextAlign = "1",
											nTextHAlign = "1",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "1",
											text = "Please log in account",
											touchAble = "True",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = -219,
												PositionY = 2,
												LeftPositon = 275,
												TopPosition = 491,
												relativeToName = "Panel",
											},
											width = "300",
											ZOrder = "8",
										},
									},
								},
								{
									controlID = "btn_login_bg_Panel_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
									UUID = "ba49e710_62df_4af1_bc95_a844c8d5eb6a",
									anchorPoint = "False",
									anchorPointX = "0.5",
									anchorPointY = "0.5",
									backGroundScale9Enable = "False",
									classname = "MEButton",
									ClickHighLightEnabled = "True",
									dstBlendFunc = "771",
									flipX = "False",
									flipY = "False",
									height = "57",
									HitType = 
									{
										nHitType = 1,
										nXpos = -27,
										nYpos = -36,
										nHitWidth = 503,
										nHitHeight = 109
									},
									ignoreSize = "True",
									name = "btn_login",
									normal = "ui_new/login/zh_jr.png",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionY = -260,
										RightPosition = 102,
										BottomPosition = 35,
										relativeToName = "Panel",
										nGravity = 3,
										nAlign = 9
									},
									UItype = "Button",
									width = "445",
									ZOrder = "4",
								},
							},
						},
					},
				},
				{
					controlID = "btn_fanhui_Panel-LoginNoticePage_group_login_Game",
					UUID = "aeaf5556_9a45_4f9c_b61a_10d33cbfebff",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEButton",
					ClickHighLightEnabled = "True",
					dstBlendFunc = "771",
					flipX = "False",
					flipY = "False",
					height = "56",
					HitType = 
					{
						nHitType = 2,
						nRadius = 50,
					},
					ignoreSize = "True",
					name = "btn_fanhui",
					normal = "ui_new/common/xx_fanhui_btn.png",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						PositionX = 42,
						PositionY = 682,
						relativeToName = "Panel",
						nType = 3,
					},
					UItype = "Button",
					width = "83",
					ZOrder = "5",
				},
				{
					controlID = "panel_close_Panel-LoginNoticePage_group_login_Game",
					UUID = "2f37bb2c_ee0b_482a_ba36_7bb600b4b8c3",
					anchorPoint = "False",
					anchorPointX = "0",
					anchorPointY = "0",
					backGroundScale9Enable = "False",
					bgColorOpacity = "100",
					bIsOpenClipping = "False",
					classname = "MEPanel",
					colorType = "1;SingleColor:#FF000000;GraduallyChangingColorStart:#FFFFFFFF;GraduallyChangingColorEnd:#FFFFFFFF;vectorX:0;vectorY:0",
					DesignHeight = "640",
					DesignType = "0",
					DesignWidth = "960",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "False",
					name = "panel_close",
					PanelRelativeSizeModel = 
					{
						PanelRelativeEnable = true,
					},
					sizepercentx = "85",
					sizepercenty = "100",
					sizeType = "0",
					srcBlendFunc = "1",
					touchAble = "True",
					UILayoutViewModel = 
					{
						relativeToName = "Panel",
						nType = 3,
					},
					uipanelviewmodel = 
					{
						Layout="Absolute",
						nType = "0"
					},
					visible = "False",
					width = "960",
					ZOrder = "5",
				},
				{
					controlID = "img_title_Panel-LoginNoticePage_group_login_Game",
					UUID = "e8f1ed20_5045_4e4a_8c6d_74a03642534a",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "149",
					ignoreSize = "True",
					name = "img_title",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/logo.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 950,
						PositionY = 632,
						RightPosition = 15,
						TopPosition = 3,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					width = "311",
					ZOrder = "4",
				},
				{
					controlID = "img_gonggaodi_Panel-LoginNoticePage_group_login_Game",
					UUID = "8200298d_0811_438b_a992_ba46871e31f0",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "442",
					ignoreSize = "True",
					name = "img_gonggaodi",
					scaleX = "0.9",
					scaleY = "0.9",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/xf_gonggao.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 560,
						PositionY = 465,
						TopPosition = 46,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 2
					},
					width = "644",
					ZOrder = "88",
					components = 
					{
						
						{
							controlID = "img_gonggao_img_gonggaodi_Panel-LoginNoticePage_group_login_Game",
							UUID = "9b927463_27ee_48b1_8a42_4aa0adea0bc0",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "24",
							ignoreSize = "True",
							name = "img_gonggao",
							scaleX = "0.9",
							scaleY = "0.9",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/xf_gonggao2.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 172,
							},
							visible = "False",
							width = "153",
							ZOrder = "1",
						},
						{
							controlID = "bg_helpList_img_gonggaodi_Panel-LoginNoticePage_group_login_Game",
							UUID = "2742c5aa_0012_4897_ae1f_a92012ab8a0e",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "True;capInsetsX:0;capInsetsY:0;capInsetsWidth:0;capInsetsHeight:0",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "390",
							ignoreSize = "False",
							name = "bg_helpList",
							opacity = "0",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 1,
							},
							width = "550",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "list_help_bg_helpList_img_gonggaodi_Panel-LoginNoticePage_group_login_Game",
									UUID = "eb5e0e1d_b8bd_477b_9a36_5a8043d30d51",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0",
									backGroundScale9Enable = "False",
									bgColorOpacity = "50",
									bIsOpenClipping = "True",
									bounceEnable = "False",
									classname = "MEScrollView",
									colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
									direction = "1",
									dstBlendFunc = "771",
									height = "300",
									ignoreSize = "False",
									innerHeight = "300",
									innerWidth = "530",
									name = "list_help",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "1",
									touchAble = "True",
									UILayoutViewModel = 
									{
										PositionX = -265,
										PositionY = -178,
									},
									uipanelviewmodel = 
									{
										Layout="Absolute",
										nType = "0"
									},
									width = "530",
									ZOrder = "1",
									components = 
									{
										
										{
											controlID = "txt_content_list_help_bg_helpList_img_gonggaodi_Panel-LoginNoticePage_group_login_Game",
											UUID = "7c46d98f_2d10_4935_869f_7e71ca5f5333",
											anchorPoint = "False",
											anchorPointX = "0",
											anchorPointY = "1",
											classname = "METextArea",
											ColorMixing = "#FF000000",
											dstBlendFunc = "771",
											fontName = "simhei",
											fontShadow = 
											{
												IsShadow = false,
												ShadowColor = "#FFFFFFFF",
												ShadowAlpha = 255,
												OffsetX = 0,
												OffsetY = 0,
											},
											fontSize = "26",
											fontStroke = 
											{
												IsStroke = true,
												StrokeColor = "#FFFFFFFF",
												StrokeSize = 1,
											},
											hAlignment = "0",
											height = "0",
											ignoreSize = "False",
											name = "txt_content",
											sizepercentx = "0",
											sizepercenty = "0",
											sizeType = "0",
											srcBlendFunc = "770",
											text = "Hey Man~~ adadasd",
											touchAble = "False",
											touchScaleEnable = "False",
											UILayoutViewModel = 
											{
												PositionX = 1,
												PositionY = 380,
											},
											vAlignment = "0",
											width = "530",
											ZOrder = "1",
										},
									},
								},
							},
						},
						{
							controlID = "bg_title_img_gonggaodi_Panel-LoginNoticePage_group_login_Game",
							UUID = "30659505_bdb7_491a_8298_a587e2b05b1a",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "160",
							ignoreSize = "True",
							name = "bg_title",
							scaleX = "0.824",
							scaleY = "0.82",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/bg_gonggao.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -1,
								PositionY = 174,
							},
							width = "826",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "Image_LoginNoticePage_1_Panel-LoginNoticePage_group_login_Game",
					UUID = "66a3355a_091c_40f2_a56a_7ba252e24b56",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "24",
					ignoreSize = "True",
					name = "Image_LoginNoticePage_1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/img_zg.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 560,
						PositionY = 12,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 8
					},
					visible = "False",
					width = "846",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/login/bg_1.png",
			"ui_new/login/bg_2.png",
			"ui_new/login/zh_xuanqu.png",
			"ui_new/login/zh_hq.png",
			"ui_new/login/zh_zc.png",
			"ui_new/login/zh_zhanghao.png",
			"ui_new/login/zh_qh.png",
			"ui_new/login/zh_jr.png",
			"ui_new/common/xx_fanhui_btn.png",
			"ui_new/login/logo.png",
			"ui_new/login/xf_gonggao.png",
			"ui_new/login/xf_gonggao2.png",
			"ui_new/login/bg_gonggao.png",
			"ui_new/login/img_zg.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

