local t = 
{
	version = 1,
	components = 
	{
		
		{
			controlID = "Panel-UpdateLayer_group_login_Game",
			UUID = "e49e43dc_cb94_4a60_87ca_336d53e08798",
			anchorPoint = "False",
			anchorPointX = "0",
			anchorPointY = "0",
			backGroundScale9Enable = "False",
			bgColorOpacity = "50",
			bIsOpenClipping = "False",
			classname = "MEPanel",
			colorType = "0;SingleColor:#FFE6E6E6;GraduallyChangingColorStart:#00000000;GraduallyChangingColorEnd:#00000000;vectorX:0;vectorY:0",
			DesignHeight = "640",
			DesignType = "0",
			DesignWidth = "960",
			dstBlendFunc = "771",
			height = "640",
			ignoreSize = "False",
			name = "Panel",
			PanelRelativeSizeModel = 
			{
				PanelRelativeEnable = true,
			},
			sizepercentx = "0",
			sizepercenty = "0",
			sizeType = "0",
			srcBlendFunc = "1",
			touchAble = "False",
			UILayoutViewModel = 
			{
				nType = 3,
			},
			uipanelviewmodel = 
			{
				Layout="Relative",
				nType = "3"
			},
			width = "960",
			ZOrder = "2",
			components = 
			{
				
				{
					controlID = "bg_Panel-UpdateLayer_group_login_Game",
					UUID = "1f6424f4_3884_4e26_9ef6_407a88dce4da",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					ColorMixing = "#FF3D3D3D",
					dstBlendFunc = "771",
					height = "640",
					ignoreSize = "True",
					name = "bg",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "770",
					texturePath = "ui_new/login/img_bg.jpg",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 560,
						PositionY = 355,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 5
					},
					width = "1136",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "Image_LoginLayer_2_bg_Panel-UpdateLayer_group_login_Game",
							UUID = "d8e32d73_76c8_40ae_b420_65d3d5ad66f4",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Image_LoginLayer_2",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/bg_2.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -130,
								PositionY = -97,
							},
							visible = "False",
							width = "64",
							ZOrder = "1",
						},
						{
							controlID = "Image_LoginLayer_1_bg_Panel-UpdateLayer_group_login_Game",
							UUID = "b3fd96b3_f2c6_416b_9feb_9d079d0108d6",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "Image_LoginLayer_1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/bg_1.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = -163,
							},
							visible = "False",
							width = "64",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "img_title_Panel-UpdateLayer_group_login_Game",
					UUID = "aa3ba18b_7a78_4634_b878_3b1789d8da32",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "145",
					ignoreSize = "True",
					name = "img_title",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/logo.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 931,
						PositionY = 634,
						RightPosition = 15,
						TopPosition = 3,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 3,
						nAlign = 3
					},
					width = "347",
					ZOrder = "1",
				},
				{
					controlID = "bg_update_Panel-UpdateLayer_group_login_Game",
					UUID = "59f7d6f8_b805_46af_9938_de463fbdd2fe",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "106",
					ignoreSize = "True",
					name = "bg_update",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/load_lan.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 560,
						PositionY = 194,
						TopPosition = 463,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 2
					},
					visible = "False",
					width = "960",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "img_jiazai_bg_update_Panel-UpdateLayer_group_login_Game",
							UUID = "d2234a78_e517_4e1b_86f8_051bfd00dba7",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "64",
							ignoreSize = "True",
							name = "img_jiazai",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/load_jiazai.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -209,
								PositionY = 50,
								LeftPositon = 182,
								TopPosition = 489,
								relativeToName = "Panel",
							},
							width = "64",
							ZOrder = "1",
							components = 
							{
								
								{
									controlID = "txt_loading_img_jiazai_bg_update_Panel-UpdateLayer_group_login_Game",
									UUID = "4d8ac3d5_f6f3_441d_b708_53151aa18484",
									anchorPoint = "False",
									anchorPointX = "0",
									anchorPointY = "0.5",
									classname = "MELabel",
									ColorMixing = "#FFFFFF00",
									compPath = "luacomponents.common.MEIconLabel",
									dstBlendFunc = "771",
									FontColor = "#FFFFFFFF",
									fontName = "simhei",
									fontShadow = 
									{
										IsShadow = false,
										ShadowColor = "#FFFFFFFF",
										ShadowAlpha = 255,
										OffsetX = 0,
										OffsetY = 0,
									},
									fontSize = "50",
									fontStroke = 
									{
										IsStroke = false,
										StrokeColor = "#FFE6E6E6",
										StrokeSize = 1,
									},
									height = "66",
									ignoreSize = "True",
									name = "txt_loading",
									nTextAlign = "1",
									nTextHAlign = "1",
									sizepercentx = "0",
									sizepercenty = "0",
									sizeType = "0",
									srcBlendFunc = "770",
									text = "Updating, downloaded ",
									touchAble = "False",
									touchScaleEnable = "False",
									UILayoutViewModel = 
									{
										PositionX = 94,
										PositionY = 10,
										TopPosition = 270,
										relativeToName = "Panel",
										nGravity = 6,
										nAlign = 2
									},
									width = "549",
									ZOrder = "1",
								},
							},
						},
					},
				},
				{
					controlID = "bg_bar_Panel-UpdateLayer_group_login_Game",
					UUID = "9213d1e8_0b65_4aed_8f06_d3898d9cda6a",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					backGroundScale9Enable = "False",
					classname = "MEImage",
					dstBlendFunc = "771",
					height = "44",
					ignoreSize = "True",
					name = "bg_bar",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "1",
					texturePath = "ui_new/login/load_jindudi.png",
					touchAble = "False",
					UILayoutViewModel = 
					{
						PositionX = 560,
						PositionY = 251,
						TopPosition = 437,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 2
					},
					width = "942",
					ZOrder = "1",
					components = 
					{
						
						{
							controlID = "bar_load_bg_bar_Panel-UpdateLayer_group_login_Game",
							UUID = "4d3982d9_6dbe_4eae_b93e_a5fe51e4c050",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MELoadingBar",
							direction = "0",
							dstBlendFunc = "771",
							height = "20",
							ignoreSize = "True",
							name = "bar_load",
							percent = "50",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texture = "ui_new/login/load_jindu.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 5,
								relativeToName = "Panel",
							},
							width = "489",
							ZOrder = "1",
						},
						{
							controlID = "bar_update_bg_bar_Panel-UpdateLayer_group_login_Game",
							UUID = "454d45e5_87b3_42c8_890a_ab177d5a646d",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "20",
							ignoreSize = "True",
							name = "bar_update",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/load_jindu.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionY = 2,
								relativeToName = "Panel",
							},
							visible = "False",
							width = "489",
							ZOrder = "1",
						},
						{
							controlID = "img_liang_bg_bar_Panel-UpdateLayer_group_login_Game",
							UUID = "980af1e3_afb5_4c8e_8c74_3a06cca9d286",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							backGroundScale9Enable = "False",
							classname = "MEImage",
							dstBlendFunc = "771",
							height = "37",
							ignoreSize = "True",
							name = "img_liang",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "1",
							texturePath = "ui_new/login/img_liang.png",
							touchAble = "False",
							UILayoutViewModel = 
							{
								PositionX = -242,
								PositionY = 6,
							},
							width = "15",
							ZOrder = "1",
						},
						{
							controlID = "txt_update_bg_bar_Panel-UpdateLayer_group_login_Game",
							UUID = "7692bb1a_96cc_4d6b_80ad_00efd54e262c",
							anchorPoint = "False",
							anchorPointX = "0.5",
							anchorPointY = "0.5",
							classname = "MELabel",
							compPath = "luacomponents.common.MEIconLabel",
							dstBlendFunc = "771",
							FontColor = "#FFFFFFFF",
							fontName = "simhei",
							fontShadow = 
							{
								IsShadow = false,
								ShadowColor = "#FFFFFFFF",
								ShadowAlpha = 255,
								OffsetX = 0,
								OffsetY = 0,
							},
							fontSize = "18",
							fontStroke = 
							{
								IsStroke = false,
								StrokeColor = "#FFE6E6E6",
								StrokeSize = 1,
							},
							height = "24",
							ignoreSize = "True",
							name = "txt_update",
							nTextAlign = "1",
							nTextHAlign = "1",
							sizepercentx = "0",
							sizepercenty = "0",
							sizeType = "0",
							srcBlendFunc = "770",
							text = "Updating, downloaded ",
							touchAble = "False",
							touchScaleEnable = "False",
							UILayoutViewModel = 
							{
								PositionX = 2,
								PositionY = 8,
								TopPosition = 270,
								relativeToName = "Panel",
								nGravity = 6,
								nAlign = 2
							},
							width = "201",
							ZOrder = "1",
						},
					},
				},
				{
					controlID = "txt_chat_Panel-UpdateLayer_group_login_Game",
					UUID = "68e17c86_156b_4ae3_8239_156f23039069",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					classname = "MELabel",
					compPath = "luacomponents.common.MEIconLabel",
					dstBlendFunc = "771",
					FontColor = "#FFFFFFFF",
					fontName = "simhei",
					fontShadow = 
					{
						IsShadow = false,
						ShadowColor = "#FFFFFFFF",
						ShadowAlpha = 255,
						OffsetX = 0,
						OffsetY = 0,
					},
					fontSize = "24",
					fontStroke = 
					{
						IsStroke = false,
						StrokeColor = "#FFE6E6E6",
						StrokeSize = 1,
					},
					height = "32",
					ignoreSize = "True",
					name = "txt_chat",
					nTextAlign = "1",
					nTextHAlign = "1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "770",
					text = "Engrave Gems to increase equipment power!",
					touchAble = "False",
					touchScaleEnable = "False",
					UILayoutViewModel = 
					{
						PositionX = 560,
						PositionY = 196,
						TopPosition = 498,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 6,
						nAlign = 2
					},
					width = "516",
					ZOrder = "1",
				},
				{
					controlID = "txt_version_Panel-UpdateLayer_group_login_Game",
					UUID = "7702d6bd_1f15_4ff9_a4e7_63929d481faf",
					anchorPoint = "False",
					anchorPointX = "0.5",
					anchorPointY = "0.5",
					classname = "MELabel",
					compPath = "luacomponents.common.MEIconLabel",
					dstBlendFunc = "771",
					FontColor = "#FFFFFFFF",
					fontName = "simhei",
					fontShadow = 
					{
						IsShadow = false,
						ShadowColor = "#FFFFFFFF",
						ShadowAlpha = 255,
						OffsetX = 0,
						OffsetY = 0,
					},
					fontSize = "18",
					fontStroke = 
					{
						IsStroke = false,
						StrokeColor = "#FFE6E6E6",
						StrokeSize = 1,
					},
					height = "0",
					ignoreSize = "False",
					name = "txt_version",
					nTextAlign = "1",
					nTextHAlign = "1",
					scaleY = "1.1",
					sizepercentx = "0",
					sizepercenty = "0",
					sizeType = "0",
					srcBlendFunc = "770",
					text = "Current version 123",
					touchAble = "False",
					touchScaleEnable = "False",
					UILayoutViewModel = 
					{
						PositionX = 98,
						PositionY = 62,
						LeftPositon = 53,
						BottomPosition = 22,
						relativeToName = "Panel",
						nType = 3,
						nGravity = 4,
						nAlign = 7
					},
					width = "90",
					ZOrder = "1",
				},
			},
		},
	},
	actions = 
	{
		
	},
	respaths = 
	{
		textures = 
		{
			"ui_new/login/img_bg.jpg",
			"ui_new/login/bg_2.png",
			"ui_new/login/bg_1.png",
			"ui_new/login/logo.png",
			"ui_new/login/load_lan.png",
			"ui_new/login/load_jiazai.png",
			"ui_new/login/load_jindudi.png",
			"ui_new/login/load_jindu.png",
			"ui_new/login/img_liang.png",
		},
		armatures = 
		{
			
		},
		movieclips = 
		{
			
		},
	},
}
return t

