local mapArray = MEMapArray:new()
mapArray:push({ id = 1, color = "#000000", describe = "Trước khi thi đấu, bạn có thể cài đặt đội hình tấn công và phòng thủ"})
mapArray:push({ id = 2, color = "#000000", describe = "Nếu chưa cài đặt thì mặc định sẽ dùng trận hình hiện tại của bạn"})
mapArray:push({ id = 3, color = "#000000", describe = "giao đấu, dùng bố trận tấn công khiêu chiến bố trận phòng thủ đối phương"})
mapArray:push({ id = 4, color = "#000000", describe = "Mỗi lần tấn công thắng và phòng thủ thắng đều có thể nhận điểm, liên thắng càng cao điểm càng cao"})
mapArray:push({ id = 5, color = "#000000", describe = "Sau khi thi đấu điểm kết thúc sẽ căn cứ xếp hạng điểm trao thưởng, điểm càng cao thưởng càng cao"})
mapArray:push({ id = 6, color = "#000000", describe = "Quà đấu điểm phát qua thư vào 22:00 trong ngày"})
mapArray:push({ id = 7, color = "#000000", describe = "Top 8 tuyển thủ thi đấu điểm có thể vào thi đấu tranh bá ngày hôm sau"})
mapArray:push({ id = 8, color = "#000000", describe = "Thi đấu tranh bá dùng chế độ tự động chiến đấu 2 bên thi đấu"})
mapArray:push({ id = 9, color = "#000000", describe = "Cách phân phối thi đấu tranh bá dùng hạng 1 thi đấu điểm giao đấu hạng 8; hạng 2 giao đấu hạng 7; hạng 3 giao đấu hạng 6; hạng 4 giao đấu hạng 5"})
mapArray:push({ id = 10, color = "#000000", describe = "Thời gian thi đấu Tứ Kết là 12:00-13:00; bán kết là 13:00-15:00; chung kết là 15:00-18:00"})
mapArray:push({ id = 11, color = "#000000", describe = "5 phút trước khi thi đấu kết thúc là thời gian giao đấu, người chơi không thể đặt cược hoặc bố trận"})
mapArray:push({ id = 12, color = "#000000", describe = "Cược thắng đồng và thưởng xếp hạng thi đấu tranh bá lập tức phát sau khi thi đấu kết thúc"})
mapArray:push({ id = 31, color = "#000000", describe = "Tướng đạt lv10 trở lên mới có thể vượt Nhạn Môn Quan. "})
mapArray:push({ id = 32, color = "#000000", describe = "Khi vượt Nhạn Môn Quan, có thể cổ vũ đội; Mỗi lần cổ vũ đều có thể nâng cao cho toàn thuộc tính của tất cả tướng trong đội phần trăm nhất định. "})
mapArray:push({ id = 33, color = "#000000", describe = "Lượt cổ vũ đội mỗi ngày có giới hạn, VIP càng cao, lượt cổ vũ càng nhiều. "})
mapArray:push({ id = 34, color = "#000000", describe = "Khi vượt Nhạn Môn Quan, HP 2 bên địch ta sẽ không reset, tổng điểm nộ khí sẽ không xóa sạch. "})
mapArray:push({ id = 35, color = "#000000", describe = "Tướng đã tử trận sẽ không hồi sinh. "})
mapArray:push({ id = 36, color = "#000000", describe = "Liên tục vượt 4 ải, có thể mở thêm Rương. "})
mapArray:push({ id = 37, color = "#000000", describe = "24:00 mỗi ngày làm mới lượt reset, lượt reset 1 ngày 1 lần, không cộng dồn; VIP có nhiều lượt reset hơn, 2 ngày 2 lần, không cộng dồn. "})
mapArray:push({ id = 38, color = "#000000", describe = "Nhấp reset xong, tiến độ hiện tại của Nhạn Môn Quan sẽ bị reset. "})
mapArray:push({ id = 39, color = "#000000", describe = "VIP có thể dùng chức năng càn quét, trực tiếp nhận thưởng ải đã vượt trước đó. "})
mapArray:push({ id = 40, color = "#000000", describe = "Càn quét chỉ giới hạn dùng ngay sau khi reset, nếu sau reset thủ công vượt ải thì lần Nhạn Môn Quan này không ứng dụng chức năng càn quét; 1 lần chiến đấu Nhạn Môn Quan chỉ có thể càn quét 1 lần. "})
mapArray:push({ id = 41, color = "#000000", describe = "Ải càn quét chỉ giới hạn ải chiến đấu, ải Rương mở theo ải chiến đấu đã vượt, càn quét xong cần mở tay rương. "})
mapArray:push({ id = 42, color = "#000000", describe = "Sau khi số ải chiến đấu hôm qua vượt giảm nửa là số ải hôm sau có thể càn quét. "})
mapArray:push({ id = 43, color = "#000000", describe = "Sau khi reset lần 2 hôm nay, có thể càn quét tới chỗ đã vượt ải lần đầu hôm nay. "})
mapArray:push({ id = 44, color = "#000000", describe = "Phân chia càn quét hôm nay ngày mai lúc 24：00. "})
mapArray:push({ id = 61, color = "#000000", describe = "Tướng trợ chiến có thể giúp Tướng ra trận tăng duyên phận"})
mapArray:push({ id = 62, color = "#000000", describe = "Cùng 1 tướng không thể cùng ra trận và trợ chiến"})
mapArray:push({ id = 63, color = "#000000", describe = "Tướng lv10 trở lên mới được trợ chiến Nhạn Môn Quan"})
mapArray:push({ id = 64, color = "#000000", describe = "Tướng vàng mỗi ngày có thể trợ chiến 3 lần, tướng phẩm chất khác mỗi ngày 1 lần"})
mapArray:push({ id = 65, color = "#000000", describe = " Cùng 1 hảo hữu, mỗi ngày chỉ có thể trợ chiến 1 lần hoặc trực tiếp được trợ chiến 1 lần"})
mapArray:push({ id = 66, color = "#000000", describe = "Hảo hữu trợ chiến tướng nếu cung cấp cùng duyên phận với tướng của mình, sẽ không kích phát lại hiệu quả duyên phận"})
mapArray:push({ id = 80, color = "#000000", describe = "Nhấp khiêu chiến, mục khiêu chiến có thể chọn nhiều hoặc không chọn, mục khiêu chiến được chọn càng nhiều thưởng càng lớn"})
mapArray:push({ id = 81, color = "#000000", describe = "Nhấp nút Đổi 1 loạt trong giao diện khiêu chiến, sẽ đổi mục khiêu chiến có thể chọn hiện tại"})
mapArray:push({ id = 82, color = "#000000", describe = "Khiêu chiến kết thúc, nếu có mục khiêu chiến đã chọn chưa hoàn thành, thì phán là thất bại, cần reset tiến độ hiện tại khiêu chiến lại"})
mapArray:push({ id = 83, color = "#000000", describe = "Ngọc Vô Lượng ải tạo ra, có thể dùng để nâng cao thuộc tính cổ vũ sau khi vượt ải mỗi tầng nhận rương"})
mapArray:push({ id = 84, color = "#000000", describe = "Trong giao diện cổ vũ, 3 thuộc tính nâng cao chỉ có thể chọn 1"})
mapArray:push({ id = 85, color = "#000000", describe = "Reset xong có thể trực tiếp càn quét hoàn thành ải đã hoàn thành tất cả mục tiêu"})
mapArray:push({ id = 86, color = "#000000", describe = "Nhấp reset, tiến độ hiện tại của Vô Lượng Sơn Bắc Quật sẽ bị reset"})
mapArray:push({ id = 100, color = "#000000", describe = "Kinh mạch mỗi 5 cấp có thể đột phá 1 lần, đột phá xong điểm trưởng thành nâng cao"})
mapArray:push({ id = 101, color = "#000000", describe = "Kinh mạch mỗi khi đột phá 1 lần, đều tốn tỉ lệ thành công, tỉ lệ thành công mỗi 30 phút hồi phục 5%"})
mapArray:push({ id = 102, color = "#000000", describe = "Đột phá kinh mạch bất luận thành công hay thất bại, đều tốn Tinh Lộ và tỉ lệ thành công"})
mapArray:push({ id = 103, color = "#000000", describe = "Khi tỉ lệ đột phá kinh mạch thành công là 10% sẽ không giảm thấp nữa"})
mapArray:push({ id = 104, color = "#000000", describe = "Tinh Lộ đột phá kinh mạch dùng, có thể nhận trong Vô Lượng Sơn Bắc Quật"})
mapArray:push({ id = 119, color = "#000000", describe = "Kết thúc mỗi trận HP địch sẽ không hồi phục, nếu sau chiến đấu HP địch nhiều hơn HP trước chiến đấu, sẽ tự động reset về HP trước chiến đấu"})
mapArray:push({ id = 120, color = "#000000", describe = "Cùng 1 BOSS, cùng 1 thời gian chỉ có thể có 1 thành viên bang khiêu chiến"})
mapArray:push({ id = 121, color = "#000000", describe = "Chỉ cần khiêu chiến bất luận thắng thua đều sẽ nhận thưởng tổng kết, thưởng đánh bại sẽ gửi qua thư cho người chơi sau khi đánh bại"})
mapArray:push({ id = 122, color = "#000000", describe = "Bang đầu tiên vượt ải chương sẽ lên danh sách vượt ải lần đầu của chương, và lưu mãi mãi, bang sau sẽ có thể cạnh tranh danh sách tốc độ vượt ải"})
mapArray:push({ id = 123, color = "#000000", describe = "Mỗi ngày mỗi chương đều có thể khiêu chiến 2 lần, 24:00 reset lượt"})
mapArray:push({ id = 124, color = "#000000", describe = "Reset chương có thể lập tức reset lượt khiêu chiến chương này"})
mapArray:push({ id = 125, color = "#000000", describe = "Chiến thắng không tính lượt, và có thể nhận x2 thưởng khiêu chiến"})
mapArray:push({ id = 126, color = "#000000", describe = "Để không ảnh hưởng trải nghiệm của thành viên bang khác, tối đa dừng ở giao diện khiêu chiến 2 phút"})
mapArray:push({ id = 127, color = "#000000", describe = "Để không ảnh hưởng trải nghiệm của thành viên bang khác, tối đa dừng ở giao diện tổng kết 20 giây"})
mapArray:push({ id = 128, color = "#000000", describe = "Để không ảnh hưởng trải nghiệm của thành viên bang khác, chiến đấu Hậu Sơn tối đa duy trì 10 phút"})
mapArray:push({ id = 129, color = "#000000", describe = "Sau 24：00 ngày thứ 2 vào bang mới, mới có thể nhận thưởng đánh bại Hậu Sơn"})
mapArray:push({ id = 130, color = "#000000", describe = "Bang Chủ/Phó bang chủ có teher thông qua nghiên cứu mở kỹ năng hoặc nâng cao giới hạn cấp kỹ năng"})
mapArray:push({ id = 131, color = "#000000", describe = "Kế thừa sẽ che cấp kỹ năng của người kế thừa lên cấp kỹ năng của người được kế thừa"})
mapArray:push({ id = 132, color = "#000000", describe = "Nâng cao cấp bang, có thể nâng cao giới hạn cấp kỹ năng nghiên cứu"})
mapArray:push({ id = 133, color = "#000000", describe = "Buff sát thương kỹ năng không gồm hiệu quả trị liệu"})
mapArray:push({ id = 134, color = "#000000", describe = "Buff sát thương liên tục là tăng trên điểm sát thương cuối cùng, chứ không phải trừ % máu"})
mapArray:push({ id = 135, color = "#000000", describe = "Đúc lại chia thành 5 phẩm: Hỏng, Xước, Hoàn Mỹ, Đúc Thần, Thiên Công. Mỗi lần đúc lại chỉ ngẫu nhiên chia lại thuộc tính giữa cấp này và cấp sau"})
mapArray:push({ id = 136, color = "#000000", describe = "5 rãnh đều có thể đúc nhiều lần, mỗi lần đúc lại nhất định tăng thuộc tính"})
mapArray:push({ id = 137, color = "#000000", describe = "2 rãnh hư hỏng, nhận thêm 1 lỗ Ngọc"})
mapArray:push({ id = 138, color = "#000000", describe = "3 ô đều là Xước, t.tính kèm tăng lên 10%"})
mapArray:push({ id = 139, color = "#000000", describe = "2 ô đều là Hoàn Mỹ, t.tính kèm tăng lên 20%"})
mapArray:push({ id = 140, color = "#000000", describe = "3 ô đều là Hoàn Mỹ, t.tính kèm tăng lên 30%"})
mapArray:push({ id = 141, color = "#000000", describe = "1 ô Đúc Thần, t.tính kèm tăng lên 40%"})
mapArray:push({ id = 142, color = "#000000", describe = "2 ô Đúc Thần, t.tính kèm tăng lên 50%"})
mapArray:push({ id = 143, color = "#000000", describe = "3 ô Đúc Thần, t.tính kèm tăng lên 60%"})
mapArray:push({ id = 160, color = "#000000", describe = "4 ô Đúc Thần, t.tính kèm tăng lên 70%"})
mapArray:push({ id = 161, color = "#000000", describe = "5 rãnh Thần Chú, nhận thêm 1 thuộc tính kèm "})
mapArray:push({ id = 162, color = "#000000", describe = "3 ô Thiên Công, t.tính kèm tăng lên 80%"})
mapArray:push({ id = 163, color = "#000000", describe = "4 ô Thiên Công, t.tính kèm tăng lên 90%"})
mapArray:push({ id = 164, color = "#000000", describe = "5 ô Thiên Công, t.tính kèm tăng lên 100%"})
mapArray:push({ id = 165, color = "#000000", describe = "Khi đúc lại, có thể dùng trang bị giống nhau thay thế Đá Đúc Lại cao cấp"})
mapArray:push({ id = 166, color = "#000000", describe = "Khi tiêu hao trang bị đã đúc lại, chỉ trả lại 1 phần mảnh trang bị đã tiêu hao 1 lần đúc lại mỗi rãnh"})
mapArray:push({ id = 144, color = "#000000", describe = "2 Khoáng Động không thể dùng cùng 1 tướng khai khoáng"})
mapArray:push({ id = 145, color = "#000000", describe = "Người chơi cần đánh bại người khai khoáng và Hộ Vệ mới cso thể cướp khoáng thành công"})
mapArray:push({ id = 146, color = "#000000", describe = "Khi cướp cùng 1 người, giữa nhiều lần cướp không hồi phục trạng thái"})
mapArray:push({ id = 147, color = "#000000", describe = "Khi hảo hữu và thành viên bang là cùng 1 người, chỉ có thể mời 1 lần"})
mapArray:push({ id = 148, color = "#000000", describe = "Mỗi lần khai khoáng chỉ có thể bị cướp thành công 1 lần"})
mapArray:push({ id = 149, color = "#000000", describe = "Để không ảnh hưởng trải nghiệm của người chơi khác, giao diện cướp tối đa duy trì 2 phút"})
mapArray:push({ id = 150, color = "#000000", describe = "Để không ảnh hưởng trải nghiệm của người chơi khác, giao diện tổng kết tối đa duy trì 20 giây"})
mapArray:push({ id = 170, color = "#000000", describe = "Bất cứ tướng nào cũng có thể phái, nhưng không phải tất cả tướng đều có thể được thuê"})
mapArray:push({ id = 171, color = "#000000", describe = "Phái tướng và đội có thể nhận đồng, thời gian phái càng dài thu nhập càng nhiều"})
mapArray:push({ id = 172, color = "#000000", describe = "Tướng và đội phái đi cần ít nhất 30 phút mới có thể về đội"})
mapArray:push({ id = 173, color = "#000000", describe = "Bạn bè có thể dùng Đồng thuê tướng và đội"})
mapArray:push({ id = 174, color = "#000000", describe = "Mỗi ngày chỉ có thể thuê 1 tướng của 1 người chơi, 1 đội của 1 người chơi"})
mapArray:push({ id = 175, color = "#000000", describe = "Căn cứ thực lực của tất cả tướng và đội xác định giá thuê"})
mapArray:push({ id = 176, color = "#000000", describe = "1 phần tiền thuê hệ thống thu hồi, 1 phần trả cho người chơi được thuê"})
mapArray:push({ id = 177, color = "#000000", describe = "Cấp VIP người chơi càng cao, tướng có thể phái càng nhiều"})
mapArray:push({ id = 178, color = "#000000", describe = "Mỗi trận chỉ có thể thuê 1 tướng, bất luận thắng thua, lính thuê không trả lại"})
mapArray:push({ id = 179, color = "#000000", describe = "Thuê tướng của tướng và người chơi (gồm tướng trợ chiến), tướng tên giống nhau không thể đồng thời ra trận hoặc trợ chiến"})
mapArray:push({ id = 190, color = "#000000", describe = "Vượt ải Vô Lượng Sơn Nam hoặc hoàn thành thêm khiêu chiến có thể nhận Tinh Nguyên"})
mapArray:push({ id = 191, color = "#000000", describe = "Truyền vào và đột phá Kỳ Môn sẽ tăng thuộc tính nhân vật chính"})
mapArray:push({ id = 192, color = "#000000", describe = "Đột phá Kỳ Môn cần đạt tới cấp đội tương ứng, và cần truyền vào Bát Quái hiện tại hoàn tất"})
mapArray:push({ id = 193, color = "#000000", describe = "Kỳ Môn mỗi khi nâng cao 5 tầng, toàn bộ tướng đều có thêm buff thuộc tính"})
mapArray:push({ id = 210, color = "#000000", describe = "Người chơi có 5 lượt chiến mỗi ngày"})
mapArray:push({ id = 211, color = "#000000", describe = "00：00 mỗi ngày reset lượt khiêu chiến"})
mapArray:push({ id = 212, color = "#000000", describe = "22：10 mỗi ngày căn cứ sát thương xếp hạng, và phát thưởng qua thư"})
mapArray:push({ id = 213, color = "#000000", describe = "Hệ thống sẽ ghi chép sát thương cao nhất người chơi khiêu chiến tạo thành, và xếp hạng"})
mapArray:push({ id = 214, color = "#000000", describe = "22：00 - 0：00 mỗi ngày là thời gian tổng kết, không thể khiêu chiến"})
mapArray:push({ id = 215, color = "#000000", describe = "Sau khi tướng bị thảo phạt mỗi giai đoạn bị đánh bại sẽ vĩnh viễn đi vào giai đoạn sau vào 0h ngày thứ 2"})
mapArray:push({ id = 216, color = "#000000", describe = "Điểm năng lực của tướng bị thảo phạt đi vào giai đoạn tiếp theo đều được tăng mạnh"})
mapArray:push({ id = 217, color = "#000000", describe = "Giai đoạn đánh bại xếp hạng từ cao tới thấp, khi 2 hoặc nhiều server trong bảng vinh dự giai đoạn đánh bại tương đồng dùng trình tự đánh bại trước sau xếp hạng từ trên xuống"})
mapArray:push({ id = 230, color = "#000000", describe = "Võ học số tầng hiện tại của nhân vật đã trang bị sẽ trả lại toàn bộ vào túi"})
mapArray:push({ id = 231, color = "#000000", describe = "Cấp chăm học khổ luyện sẽ trả lại toàn bộ thành nguyên liệu chăm học"})
mapArray:push({ id = 232, color = "#000000", describe = "Tất cả trưởng thành Tướng Hồn, kinh mạch, trang bị nhân vật sẽ chuyển đổi toàn bộ cho nhân vật mới"})
mapArray:push({ id = 250, color = "#000000", describe = "Thông qua cầu nguyện có thể nhận Tướng Hồn tương ứng"})
mapArray:push({ id = 251, color = "#000000", describe = "Nhấp tướng trái có thể đổi mục tiêu cầu nguyện"})
mapArray:push({ id = 252, color = "#000000", describe = "Không được chọn nhân vật chính"})
mapArray:push({ id = 253, color = "#000000", describe = "Mỗi ngày có 3 lần cầu nguyện"})
mapArray:push({ id = 254, color = "#000000", describe = "VIP4 sẽ tăng thêm 1 lần cầu nguyện"})
mapArray:push({ id = 255, color = "#000000", describe = "0：00 hàng ngày reset lượt cầu nguyện"})
mapArray:push({ id = 256, color = "#000000", describe = "Số ngày cầu nguyện đạt 15 ngày có thể nhận Thẻ Tướng truyền thuyết ngẫu nhiên"})
mapArray:push({ id = 270, color = "#000000", describe = "Thắng bại dùng quy tắc 3 ván thắng 2, nếu vì nguyên nhân đặc biệt tạo ra hòa, thì bang xếp hạng cao hơn trong thi đấu dự tuyển thắng"})
mapArray:push({ id = 271, color = "#000000", describe = "Số bang server vượt quá giới hạn thi đấu, căn cứ độ phồn vinh bang chọn bang"})
mapArray:push({ id = 272, color = "#000000", describe = "Độ phồn vinh bang chỉ tính lượng tăng, lượng tiêu hao sẽ không giảm bớt trị số lượng tăng, thời gian tính lượng tăng là 00:01 thứ 5 tuần trước tới 24:00 thứ 4 tuần này"})
mapArray:push({ id = 273, color = "#000000", describe = "Sau khi Tinh Anh Chiến thắng lợi, có thể giúp tất cả thành viên bang các tiểu đội nâng cao thuộc tính tương ứng"})
mapArray:push({ id = 274, color = "#000000", describe = "Sau khi trở thành Tinh Anh, vẫn có thể tham gia chiến đấu tiểu đội"})
mapArray:push({ id = 275, color = "#000000", describe = "Tinh Anh nhận thêm 20% thưởng"})
mapArray:push({ id = 276, color = "#000000", describe = "Khi đốic chiến hòa tính sát thương, người sát thương cao hơn thắng"})
mapArray:push({ id = 277, color = "#000000", describe = "22:00 thứ 6, phát thưởng Bang Phái Tranh Hùng qua thư"})
mapArray:push({ id = 278, color = "#000000", describe = "10 phút trước khi bắt đầu Bang Phái Tranh Hùng, sẽ không thể báo danh"})
mapArray:push({ id = 279, color = "#000000", describe = "Bang Chiến tự động, đội hình thông dụng đội hình phòng thủ Quần Hào Phổ"})
mapArray:push({ id = 290, color = "#000000", describe = "Trong giao diện game nhấp avatar nhân vật góc trên bên trái→nhấp nút “cài đặt”→nhấp “nhập giftcode”→“đổi”,  là có thể nhận quà"})
mapArray:push({ id = 310, color = "#000000", describe = "Tinh lọc có thể trực tiếp thắp sáng gia công"})
mapArray:push({ id = 311, color = "#000000", describe = "Nhặt hết sẽ tự động bán ra tất cả đá thải"})
mapArray:push({ id = 312, color = "#000000", describe = "Đá Cược nhanh sẽ tự động tiến hành 10 lần Đá Cược trong thử đao, cắt và mài"})
mapArray:push({ id = 313, color = "#000000", describe = "Mỗi lần Đá Cược sẽ ngẫu nhiên tạo ra Ngọc phẩm chất khác nhau, Đá Cược cao cấp Ngọc tạo ra phẩm chất cao hơn"})
mapArray:push({ id = 314, color = "#000000", describe = "Điêu khắc tối da có thể nhận Ngọc lv7"})
mapArray:push({ id = 330, color = "#000000", describe = "Đổi xong, toàn bộ thuộc tính 2 bên trang bị chuyển đổi toàn bộ"})
mapArray:push({ id = 350, color = "#000000", describe = "Bị người chơi khác đánh bại, đối phương tự động trở thành địch"})
mapArray:push({ id = 351, color = "#000000", describe = "Đánh trả thắng, địch sẽ biến mất khỏi danh sách, thất bại thì địch vẫn nằm trong danh sách"})
mapArray:push({ id = 352, color = "#000000", describe = "Điểm cọ sát của địch càng cao, thưởng đánh trả càng nhiều"})
mapArray:push({ id = 370, color = "#000000", describe = "Nhấp avatar người chơi cọ sát"})
mapArray:push({ id = 371, color = "#000000", describe = "Chủ động cọ sát với người chơi khác, thắng điểm cọ sát nâng cao, thua điểm không đổi"})
mapArray:push({ id = 372, color = "#000000", describe = "Điểm cọ sát của người chơi mục tiêu càng cao, thưởng sau khi thắng càng nhiều"})
mapArray:push({ id = 373, color = "#000000", describe = "Thưởng cọ sát và đánh trả nhận đặt vào Kho tổng kết, 24：00 chủ nhật hàng tuần tổng kết"})
mapArray:push({ id = 374, color = "#000000", describe = "Xếp hạng cọ sát càng cao, thưởng xếp hạng càng nhiều, 24：00 chủ nhật hàng tuần tổng kết"})
mapArray:push({ id = 390, color = "#000000", describe = "Thiên Thư cần học tập từng tầng, đưa vào tất cả Tinh Yếu tầng hiện tại xong mở tầng tiếp theo"})
mapArray:push({ id = 391, color = "#000000", describe = "Nghiên cứu mỗi tầng đều có rãnh Tinh Yếu, đưa vào Tinh Yếu chỉ định có thể tăng thuộc tính"})
mapArray:push({ id = 392, color = "#000000", describe = "Khi bỏ Tinh Yếu, sẽ trả lại chiến tích đưa vào Tinh Yếu này tốn"})
mapArray:push({ id = 393, color = "#000000", describe = "Sau khi reset Thiên Thư, Thiên Thư reset về 1 tầng, và trả lại tất cả chiến tích và Tinh Yếu mà bồi dưỡng Thiên Thư này tốn"})
mapArray:push({ id = 394, color = "#000000", describe = "Trân Bản và Thiện Bản Thiên Thư đột phá tới 1 sao, có thể mở lỗ Ngọc"})
mapArray:push({ id = 410, color = "#000000", describe = "Mỗi server chọn ra top 8 tuyển thủ Võ Lâm Đại Hội tuần trước tham gia Võ Lâm Đại Hội liên server"})
mapArray:push({ id = 411, color = "#000000", describe = "Tất cả chiến đấu liên server đều tự động, người chơi có thể điều chỉnh đội hình tấn công và phòng thủ của mình"})
mapArray:push({ id = 412, color = "#000000", describe = "Đội hình tấn công và phòng thủ thường dùng đội hình Võ Lâm Đại Hội"})
mapArray:push({ id = 413, color = "#000000", describe = "Thi đấu liên server tiến hành 2 trận thi đấu điểm, mỗi lần chọn top 8, tổng chọn ra 16 người chơi tham gia thi đấu loại cuối cùng"})
mapArray:push({ id = 414, color = "#000000", describe = "Trong thi đấu điểm trận 2, 8 người chơi trận đầu chọn ra không tham chiến"})
mapArray:push({ id = 430, color = "#000000", describe = "Chọn 2 tướng nhanh chóng đổi trang phục"})
mapArray:push({ id = 431, color = "#000000", describe = "Đổi trang phục sau 2 tướng đổi trang bị"})
mapArray:push({ id = 450, color = "#000000", describe = "Chỉ có tướng Tông Sư và Truyền Thuyết mới được đổi luyện cùng phẩm chất"})
mapArray:push({ id = 451, color = "#000000", describe = "2 tướng ngoài đột phá cấp, võ học đã trang bị, tất cả trưởng thành đều sẽ đổi toàn bộ"})
mapArray:push({ id = 452, color = "#000000", describe = "Võ học số tầng hiện tại 2 tướng đã trang bị trả lại hết vào túi"})
mapArray:push({ id = 453, color = "#000000", describe = "Cấp chăm học khổ luyện của võ học 2 tướng sẽ trả lại 1 phần thành nguyên liệu chăm học"})
mapArray:push({ id = 454, color = "#000000", describe = "Nhân vật chính đạt Truyền Thuyết mới được hoán công"})
mapArray:push({ id = 455, color = "#000000", describe = "Nếu 2 tướng phẩm chất khác nhau, thuộc tính tĩnh tu thừa ra sẽ đổi thành Xá Lợi trả về túi"})
mapArray:push({ id = 456, color = "#000000", describe = "Nếu 2 tướng khác phẩm chất, cấp luyện thể sẽ chuyển đổi theo tỷ lệ nhất định"})
mapArray:push({ id = 457, color = "#000000", describe = "Sau khi hoán công cấp luyện thể vượt giới hạn, sẽ trả lại Luyện Thể Đan vào túi. VD: tướng Tông Sư và Truyền Thuyết hoán công, nếu cấp luyện thể vượt giới hạn sẽ trả lại phần thừa là Thuyết Luyện Đan"})
mapArray:push({ id = 470, color = "#000000", describe = "Luyện thể gồm 6 phẩm chất Dịch Cân, Túy Cốt, Hoán Huyết, Tẩy Tủy, Uẩn Khí, Bồi Nguyên. Mỗi lần luyện thể chỉ ngẫu nhiên chia lại thuộc tính giữa cấp này và cấp sau, mỗi lần luyện thể tối thiểu +1 cấp, chắc chắn tăng thuộc tính. Giới hạn cấp đột phá do luy"})
mapArray:push({ id = 471, color = "#000000", describe = "Cấp tương ứng với phẩm chất: Dịch Cân (1-7), Túy Cốt (8-17), Hoán Huyết (18-30), Tẩy Tủy (31-60), Uẩn Khí (61-94), Bồi Nguyên (95-100)"})
mapArray:push({ id = 472, color = "#000000", describe = "Giới hạn cấp xung huyệt 2 Dịch Cân+5"})
mapArray:push({ id = 473, color = "#000000", describe = "3 Túy Cốt giới hạn cấp đột phá+1"})
mapArray:push({ id = 474, color = "#000000", describe = "2 Hoán Huyết thuộc tính cơ bản+3%"})
mapArray:push({ id = 475, color = "#000000", describe = "3 Hoán Huyết giới hạn cấp xung huyệt+10"})
mapArray:push({ id = 476, color = "#000000", describe = "1 Tẩy Tủy giới hạn cấp đột phá+2"})
mapArray:push({ id = 477, color = "#000000", describe = "2 Tẩy Tủy thuộc tính cơ bản+5%"})
mapArray:push({ id = 478, color = "#000000", describe = "3 Tẩy Tủy giới hạn cấp xung huyệt+20"})
mapArray:push({ id = 479, color = "#000000", describe = "4 Tẩy Tủy giới hạn cấp đột phá+4"})
mapArray:push({ id = 480, color = "#000000", describe = "5 Tẩy Tủy thuộc tính cơ bản+10%"})
mapArray:push({ id = 481, color = "#000000", describe = "3 Uẩn Khí, giới hạn cấp xung huyệt +25"})
mapArray:push({ id = 482, color = "#000000", describe = "4 Uẩn Khí, giới hạn cấp đột phá +5"})
mapArray:push({ id = 483, color = "#000000", describe = "5 Uẩn Khí, t.tính cơ bản +13.5%"})
mapArray:push({ id = 484, color = "#000000", describe = "3 Bồi Nguyên, giới hạn cấp xung huyệt +30"})
mapArray:push({ id = 485, color = "#000000", describe = "4 Bồi Nguyên, giới hạn cấp đột phá +6"})
mapArray:push({ id = 486, color = "#000000", describe = "5 Bồi Nguyên, t.tính cơ bản +18%"})
mapArray:push({ id = 487, color = "#000000", describe = "3 Thần Đúc, giới hạn cấp xung huyệt +35"})
mapArray:push({ id = 488, color = "#000000", describe = "4 Thần Đúc, giới hạn cấp đột phá +7"})
mapArray:push({ id = 489, color = "#000000", describe = "5 Thần Đúc, t.tính cơ bản +25%"})
mapArray:push({ id = 490, color = "#000000", describe = "Mỗi loại đội hình tương ứng bố trận hệ thống khác nhau"})
mapArray:push({ id = 491, color = "#000000", describe = "Trận Công: Vượt Ải, Vô Lượng Sơn, Ma Kha Nhai, Phục Ma Lục, Quần Hào Phổ"})
mapArray:push({ id = 492, color = "#000000", describe = "Trận Thủ: Thủ Quần Hào Phổ"})
mapArray:push({ id = 510, color = "#000000", describe = "Mỗi loại đội hình tương ứng bố trận hệ thống khác nhau"})
mapArray:push({ id = 511, color = "#000000", describe = "Trận công：Vượt ải, Vô Lượng Sơn, Ma Kha Nhai, Phục Ma Lục, Quần Hào Phổ tấn công, Hậu Sơn Bang, Bang Chiến, Võ Lâm Đại Hội tấn công"})
mapArray:push({ id = 512, color = "#000000", describe = "Trận thủ：Quần Hào Phổ phòng thủ, Võ Lâm Đại Hội phòng thủ"})
mapArray:push({ id = 513, color = "#000000", describe = "Song Trận•Công：Du ngoạn"})
mapArray:push({ id = 530, color = "#000000", describe = "Quán Á Quân Bang Phái Tranh Hùng tuần trước mỗi server tham gia Bang Phái Tranh Hùng liên server"})
mapArray:push({ id = 531, color = "#000000", describe = "Đội hình thường dừng bố trận phòng thủ"})
mapArray:push({ id = 532, color = "#000000", describe = "Sau khi Bang Phái Tranh Hùng liên server trở thành người phòng thủ, mỗi khi liên thắng 1 trận, tất cả thành viên bang tấn công tiếp theo toàn thuộc tính nâng cao 10%"})
mapArray:push({ id = 533, color = "#000000", describe = "Người tấn công đã được nâng cao thuộc tính thắng, thuộc tính tăng biến mất"})
mapArray:push({ id = 534, color = "#000000", describe = "10 phút trước khi bắt đầu chiến đấu, bang chủ/phó bang chủ có thể tùy ý đổi khu vực mục tiêu"})
mapArray:push({ id = 535, color = "#000000", describe = "Sau khi chiến đấu bắt đầu, mỗi khu vực đều sẽ loạn trình tự báo danh, sau đó theo trình tự tiến hành giao đấu 1V1, thua bị loại"})
mapArray:push({ id = 536, color = "#000000", describe = "Khi tất cả bang 1 khu vực bị loại, thì làm loạn trật tự lần nữa, bang đầu tiên tấn công người phòng thủ còn lại vòng trước"})
mapArray:push({ id = 537, color = "#000000", describe = "Trong chiến đấu mỗi ngày, bang có thể chọn lại khu vực thi đấu 1 lần"})
mapArray:push({ id = 550, color = "#000000", describe = "Tướng thần thoại có điểm chiến ý tính riêng"})
mapArray:push({ id = 551, color = "#000000", describe = "Khi chiến đấu công kích và bị đánh có thể tăng điểm chiến ý"})
mapArray:push({ id = 552, color = "#000000", describe = "Chiến ý đạt trị số nhất định có thể chủ động phóng kỹ năng thần thoại"})
mapArray:push({ id = 553, color = "#000000", describe = "Giữ avatar tướng trượt lên trên có thể phóng kỹ năng thần thoại"})
mapArray:push({ id = 570, color = "#000000", describe = "Long Môn Phá có 9 tầng, thưởng tăng theo mức độ phá trận"})
mapArray:push({ id = 571, color = "#000000", describe = "Các hiệp sĩ mỗi tầng chỉ có 1 lần chọn trận vị"})
mapArray:push({ id = 572, color = "#000000", describe = "Long Môn Phá có 3 loại trận vị, Cơ Quan Vị, Trận Nhãn Vị và Phá Trận Vị"})
mapArray:push({ id = 573, color = "#000000", describe = "Nếu mở Cơ Quan Vị, sẽ kích hoạt cơ quan, phá trận lần này thất bại"})
mapArray:push({ id = 574, color = "#000000", describe = "Nếu mở Trận Nhãn Vị, có thể nhận thưởng Túi phúc giang hồ"})
mapArray:push({ id = 575, color = "#000000", describe = "Nếu mở Phá Trận Vị, nhận 1 phần thưởng cực phẩm"})
mapArray:push({ id = 576, color = "#000000", describe = "Dùng “Tuyền Ki Kính” có thể loại bỏ 1 Cơ Quan Vị trong tầng hiện tại"})
mapArray:push({ id = 577, color = "#000000", describe = "Nếu kích hoạt nhầm cơ quan, có thể dùng “Côn Lôn Ngọc” hóa giải hồi sinh, tăng 1 lần mở trận vị"})
mapArray:push({ id = 578, color = "#000000", describe = "Ở tầng 6 hoặc 7, nếu người chơi phá trận thất bại còn có thể dùng “Hi Hoàng Điệp” hồi sinh, và reset lượt dùng “Tuyền Ki Kính” và “Côn Lôn Ngọc”"})
mapArray:push({ id = 579, color = "#000000", describe = "Tuyền Ki Kính và Côn Lôn Ngọc có lượt dùng khác nhau ở mỗi tầng"})
mapArray:push({ id = 580, color = "#000000", describe = "“Hi Hoàng Điệp” chỉ có thể dùng 1 lần trong mỗi vòng Long Môn Phá"})
mapArray:push({ id = 590, color = "#000000", describe = "Tướng cài đặt theo trật tự thông thường lần lượt tuần hoàn phóng kỹ năng trong chiến đấu"})
mapArray:push({ id = 591, color = "#000000", describe = "Tướng cài đặt trong điều kiện đặc biệt, đạt yêu cầu sẽ lập tức phóng kỹ năng"})
mapArray:push({ id = 592, color = "#000000", describe = "Nếu cùng 1 tướng cài đặt nhiều điều kiện đặc biệt, đáp ứng 1 trong số đó lập tức phóng kỹ năng"})
mapArray:push({ id = 593, color = "#000000", describe = "Khi tất cả tướng cài đặt đều đã ra trận, mặc định mới có hiệu lực"})
mapArray:push({ id = 594, color = "#000000", describe = "Theo thứ tự thông thường, nếu tướng đang CD, sẽ chờ hết CD và phóng kỹ năng của tướng này"})
mapArray:push({ id = 595, color = "#000000", describe = "Theo trình tự bình thường, nếu tướng không thể phóng kỹ năng, thì bỏ qua tướng này"})
mapArray:push({ id = 596, color = "#000000", describe = "Trong điều kiện đặc biệt, nếu tướng đang CD, thì bỏ qua tướng này"})
mapArray:push({ id = 597, color = "#000000", describe = "Trong điều kiện đặc biệt, nếu không thể phóng kỹ năng, thì bỏ qua tướng này"})
mapArray:push({ id = 598, color = "#000000", describe = "Trong điều kiện đặc biệt, nếu tướng kích hoạt giống tướng tiếp theo trong trình tự bình thường, thì coi là dùng 1 lần trình tự thường"})
mapArray:push({ id = 599, color = "#000000", describe = "Trong điều kiện đặc biệt, nếu nhiều điều kiện đồng thời kích hoạt, thì căn cứ cài đặt tướng trong điều kiện đặc biệt, lần lượt phóng kỹ năng từ trên xuống dưới"})
mapArray:push({ id = 610, color = "#000000", describe = "10:00-22:00 mỗi thứ 2 mở Luận Kiếm Phong"})
mapArray:push({ id = 611, color = "#000000", describe = "22:30 mỗi thứ 2 phát thưởng theo XH điểm"})
mapArray:push({ id = 612, color = "#000000", describe = "Chiếm lĩnh trận nhãn, có thể nhận điểm tăng theo thời gian, chiếm 1 lần tối đa duy trì 8 giờ"})
mapArray:push({ id = 613, color = "#000000", describe = "Tấn công trận nhãn của người chơi, có thể nhận thêm điểm"})
mapArray:push({ id = 614, color = "#000000", describe = "Thay đổi thời gian： Giữa khoảng thời gian khác nhau, tỉ lệ thu ích của trận nhãn khác nhau, gồm cả hiệu quả Đoàn Kết"})
mapArray:push({ id = 615, color = "#000000", describe = "Tăng ích bang： Trong tầng cao, chiếm lĩnh trận nhãn có thể tăng cho thành viên bang thuộc tính toàn đội cuối cùng của Võ Lâm Đại Hội, Bang Chiến, Luận Kiếm Phong"})
mapArray:push({ id = 616, color = "#000000", describe = "Tăng ích bang tối đa là 15%"})
mapArray:push({ id = 617, color = "#000000", describe = "Đoàn Kết： Trong tầng cao, cùng 1 server chiếm lĩnh cả 1 tầng trận nhãn, có thể nhận thêm lượng lớn điểm theo tăng trưởng thời gian"})
mapArray:push({ id = 618, color = "#000000", describe = "Tích điểm nhận trong trận nhãn tự động làm mới tính vào bảng điểm khi mất đi trận nhãn, 22：00 tổng kết"})
mapArray:push({ id = 630, color = "#000000", describe = "Mỗi lần sửa đều ngẫu nhiên thêm giảm điểm cho thuộc tính, thay thế sẽ tăng giảm điểm vào thuộc tính cũ, tiếp tục sửa thì sẽ ngẫu nhên tăng giảm điểm lại"})
mapArray:push({ id = 631, color = "#000000", describe = "Tỉ lệ tăng giảm điểm ngẫu nhiên của 3 mức sửa giống nhau"})
mapArray:push({ id = 632, color = "#000000", describe = "Thuộc tính càng gần max điểm hiện tại, độ khó nâng cao càng lớn"})
mapArray:push({ id = 633, color = "#000000", describe = "Phẩm chất và cấp tướng ảnh hưởng giới hạn thuộc tính"})
mapArray:push({ id = 634, color = "#000000", describe = "Sau khi hồi sinh hoặc quy ẩn, “Xá Lợi Tử” sẽ không trả lại"})
mapArray:push({ id = 650, color = "#000000", describe = "Thu thập tất cả tướng cần, thì kích hoạt mục này"})
mapArray:push({ id = 651, color = "#000000", describe = "Cấp mục là cấp sao đột phá tướng thấp nhất trong mục"})
mapArray:push({ id = 652, color = "#000000", describe = "Sau khi kích hoạt/tăng sao mục, vĩnh viễn kích hoạt/tăng sao, không vì tướng hồi sinh hoặc quy ẩn mà thay đổi trạng thái"})
mapArray:push({ id = 670, color = "#000000", describe = "Vô Lượng-Mộng là khiêu chiến PVE liên server, tất cả người chơi trong tổ liên server sẽ thi đấu tiến độ Vô Lượng-Mộng"})
mapArray:push({ id = 671, color = "#000000", describe = "Vô Lượng-Mộng là cơ chế mùa đấu, ban đầu sẽ reset tiến độ ải, kết thúc mùa đấu sẽ căn cứ xếp hạng phát thưởng"})
mapArray:push({ id = 672, color = "#000000", describe = "Mỗi tầng lần đầu đánh phá trong lịch sử, trong mùa đấu có thể nhận thêm thưởng"})
mapArray:push({ id = 673, color = "#000000", describe = "Sau khi ghi chép vượt ải người chơi vượt qua mùa đầu trước, có thể nhận thêm rất nhiều thưởng"})
mapArray:push({ id = 690, color = "#000000", describe = "Đá Phụ Ma được điểm Phụ Ma"})
mapArray:push({ id = 691, color = "#000000", describe = "Điểm phụ ma đạt tối đa là thành công phụ ma 1 lỗ phụ ma, nhận buff thuộc tính"})
mapArray:push({ id = 692, color = "#000000", describe = "10 lỗ phụ ma cấp hiện tại đều phụ ma xong, trang bị có thể tăng cấp, và nhận hiệu quả đặc biệt"})
mapArray:push({ id = 693, color = "#000000", describe = "Cấp tăng sao trang bị càng cao, giới hạn cấp tăng càng cao"})
mapArray:push({ id = 694, color = "#000000", describe = "Cấp tăng khác nhau, nguyên liệu tăng cấp có thể dùng khác nhau"})
mapArray:push({ id = 710, color = "#000000", describe = "Nhấp hoặc ấn giữ nguyên liệu tăng cấp có thể nhận exp gia viên"})
mapArray:push({ id = 711, color = "#000000", describe = "Đạt cấp gia viên chỉ định, tất cả tướng ra trận có thể nhận buff thuộc tính"})
mapArray:push({ id = 712, color = "#000000", describe = "Mỗi ngày có thể nhận nguyên liệu tăng cấp từ trong Vòng quay"})
mapArray:push({ id = 713, color = "#000000", describe = "Hàng ngày có 7 lần like bạn bè, mỗi lần like nhận 1 lần quay thưởng"})
mapArray:push({ id = 714, color = "#000000", describe = "Lượt quay thưởng nhận được khi like sẽ không biến mất"})
mapArray:push({ id = 715, color = "#000000", describe = "Được like 20 lần nhận thêm thưởng nguyên liệu Gia Viên"})
mapArray:push({ id = 716, color = "#000000", describe = " Hàng ngày ngẫu nhiên xuất hiện sự kiện Gia Viên trong Gia Viên của hảo hữu, đến hoàn thành sự kiện được nhận thưởng"})
mapArray:push({ id = 717, color = "#000000", describe = "Sự kiện Gia Viên cùng loại, cùng lúc chỉ được tồn tại 1, tối đa được tồn tại 3 loại sự kiện"})
mapArray:push({ id = 718, color = "#000000", describe = "Mỗi Gia Viên mỗi ngày tối thiểu được xuất hiện 4 sự kiện"})
mapArray:push({ id = 719, color = "#000000", describe = "Hỗ trợ Gia Viên chưa hoàn thành sẽ tổng kết và biến mất sau 24 tiếng"})
mapArray:push({ id = 730, color = "#000000", describe = "Sau khi nâng lên tướng truyền thuyết, có thể tăng thuộc tính trưởng thành"})
mapArray:push({ id = 731, color = "#000000", describe = "Sau khi nâng lên tướng truyền thuyết, thuộc tính luyện thể sẽ trưởng thành theo thuộc tính luyện thể của tướng truyền thuyết"})
mapArray:push({ id = 732, color = "#000000", describe = "Sau khi nâng lên tướng truyền thuyết, cấp luyện thể sẽ chuyển thành luyện thể truyền thuyết theo tỉ lệ nhất định"})
mapArray:push({ id = 733, color = "#000000", describe = "Tăng phẩm tướng, thuộc tính sửa hiện tại không đổi, giới hạn tăng"})
mapArray:push({ id = 750, color = "#000000", describe = "Mỗi lần tốn xu cổ bất kì mua vàng có thể được tặng 1 lần quay VQ Thiên Cơ"})
mapArray:push({ id = 751, color = "#000000", describe = "Mỗi khi có người tiêu Xu Vàng, tổng thưởng cộng thêm KNB với mức cố định 1 lần"})
mapArray:push({ id = 752, color = "#000000", describe = "Khi không đạt được điều kiện nhận đặc biệt, có thể giành được tất cả đạo cụ xuất hiện ở cột giữa VQ Thiên Cơ"})
mapArray:push({ id = 753, color = "#000000", describe = "Khi đạt được điều kiện nhận đặc biệt, thì nhận thưởng mặc định trong điều kiện nhận đặc biệt, chứ không phải đạo cụ xuất hiện giữa VQ Thiên Cơ"})
mapArray:push({ id = 754, color = "#000000", describe = "Ngoài thưởng đặc biệt, vật phẩm nhận trong VQ Thiên Cơ đều hưởng buff gấp bội xu"})
mapArray:push({ id = 755, color = "#000000", describe = "Mỗi khi có người chơi nhận thưởng đặc biệt, kho thưởng sẽ xóa sạch, và bắt đầu tích lũy lại"})
mapArray:push({ id = 770, color = "#000000", describe = "Lì xì bang phát ít nhất 5 người, tối đa bằng số người bang hiện tại"})
mapArray:push({ id = 771, color = "#000000", describe = "Lì xì bang là lì xì may mắn, mức ngẫu nhiên, phát xong có thể nhận trong giao diện chat bang"})
mapArray:push({ id = 772, color = "#000000", describe = "Lì xì bang phát xong tồn tại 2 giờ, quá hạn nếu còn KNB lì xì chưa nhận sẽ tự động trả lại cho người phát bằng hình thức phiếu điểm lì xì"})
mapArray:push({ id = 773, color = "#000000", describe = "Phiếu điểm có thể dùng để mua lì xì, số phiếu điểm yêu cầu giống với mức lì xì"})
mapArray:push({ id = 774, color = "#000000", describe = "Trong thời gian giải tán bang không thể phát lì xì"})
mapArray:push({ id = 775, color = "#000000", describe = "Lì xì bang nhận tới giá trị nhất định có thể mở khóa thành tựu tương ứng, và nâng cao buff thuộc tính"})
mapArray:push({ id = 776, color = "#000000", describe = "Lì xì 5000 KNB và 10000 KNB phát xong sẽ có buff thuộc tính chia % toàn đội trong 1 giờ"})
mapArray:push({ id = 777, color = "#000000", describe = "Bảng Tài Vận có thể xem xếp hạng người chơi phát mức lì xì hiệu lực của server hiện tại"})
mapArray:push({ id = 778, color = "#000000", describe = "Vào bang mới sau 24 giờ, mới có thể thu phát lì xì"})
mapArray:push({ id = 790, color = "#000000", describe = "Có thể tốn Ngũ Thạch cường hóa trận pháp"})
mapArray:push({ id = 791, color = "#000000", describe = "Thuộc tính cường hóa trận pháp có hiệu lực với tất cả tướng ra trận"})
mapArray:push({ id = 792, color = "#000000", describe = "Tướng ra trận nếu ở trong trận vị, có thể tăng thuộc tính trận vị tương ứng"})
mapArray:push({ id = 793, color = "#000000", describe = "Hiệu quả đặc biệt của trận vị có hiệu lực với tất cả tướng trên trận vị"})
mapArray:push({ id = 794, color = "#000000", describe = "Cấp sao đột phá càng cao, giới hạn cấp cường hóa càng lớn"})
mapArray:push({ id = 795, color = "#000000", describe = "Chuyển chỗ có thể ngẫu nhiên thay đổi vị trí trận vị tương ứng"})
mapArray:push({ id = 796, color = "#000000", describe = "Chuyển chỗ lần đầu mỗi trận pháp miễn phí"})
mapArray:push({ id = 797, color = "#000000", describe = "Lính thuê không nhận buff thuộc tính của trận pháp"})
mapArray:push({ id = 810, color = "#000000", describe = "Ải vượt trận, có thể đồng thời ra trận 7 tướng khiêu chiến"})
mapArray:push({ id = 811, color = "#000000", describe = "Nhấp sương mù bên cạnh ô trận đã tìm có thể xua tan sương mù"})
mapArray:push({ id = 812, color = "#000000", describe = "Nhấp rương có thể nhận thưởng"})
mapArray:push({ id = 813, color = "#000000", describe = "Trận Vệ sẽ ngăn bạn tìm khu vực xung quanh Trận Vệ"})
mapArray:push({ id = 814, color = "#000000", describe = "Trong quá trình vượt trận có thể kích hoạt Trận Pháp Huyền Quan và hiệu quả đặc biệt"})
mapArray:push({ id = 815, color = "#000000", describe = "Đánh bại Hộ Pháp tầng hiện tại có thể nhận thưởng vượt ải, đến tầng tiếp theo"})
mapArray:push({ id = 816, color = "#000000", describe = "Vượt trận có 5 tầng, đánh bại Hộ Pháp tầng  5 mở chức năng càn quét độ khó hiện tại"})
mapArray:push({ id = 817, color = "#000000", describe = "Khi vượt trận, HP 2 bên sẽ không reset"})
mapArray:push({ id = 818, color = "#000000", describe = "Trong Mê Trận khí trường mãnh liệt, sát thương liên tục mà Trận Vệ và Hộ Pháp nhận phải sẽ miễn giảm 1 phần, và miễn dịch hiệu quả Hấp Nộ"})
mapArray:push({ id = 830, color = "#000000", describe = "Nội dung tặng phiếu tặng là KNB và điểm VIP mức tương ứng, nhưng không tính vào mức hoạt động nạp"})
mapArray:push({ id = 831, color = "#000000", describe = "Mức phiếu tặng cần nhỏ hơn hoặc bằng mức nạp lần này mới có thể nhận"})
mapArray:push({ id = 832, color = "#000000", describe = "Mỗi lần nạp có thể và chỉ có thể dùng 1 tấm phiếu tặng, khi nạp tự động dùng"})
mapArray:push({ id = 833, color = "#000000", describe = "Tất cả phiếu tặng của 【Hôm nay dùng】 sẽ mất hiệu lực và biến mất lúc 0:00 ngày thứ 2, đồng thời phiếu tặng 【Ngày mai dùng】 thống nhất đổi tới 【Hôm nay dùng】 và kích hoạt trạng thái có thể chọn"})
mapArray:push({ id = 834, color = "#000000", describe = "Thẻ quà được tặng thêm sau khi nạp, không chiết khấu như đạo cụ thay thế tiền mặt"})
mapArray:push({ id = 850, color = "#000000", describe = "Mỗi lần chiêu mộ đều được Danh Vọng, chiêu mộ khác nhau Danh Vọng nhận khác nhau, sau khi mở hết sẽ không nhận tiếp."})
mapArray:push({ id = 851, color = "#000000", describe = "Đủ Danh Vọng sẽ mở mua nội dung tương ứng, mỗi nội dung đều giới hạn lượt mua"})
mapArray:push({ id = 852, color = "#000000", describe = "Mua đạo cụ hoặc tướng cần tiêu hao KNB tương ứng, khi Danh Vọng thấp hơn mức này sẽ khóa và không thể mua"})
mapArray:push({ id = 853, color = "#000000", describe = "Khi sự kiện chiêu mộ kết thúc, Danh Vọng hiện có sẽ bị xóa, hãy cố gắng dùng hết"})
mapArray:push({ id = 854, color = "#000000", describe = "00:00:00 mỗi ngày cài lại lượt mua toàn bộ đạo cụ"})
mapArray:push({ id = 870, color = "#000000", describe = "Nghiên cứu có 6 phẩm chất gồm Đọc qua, Hiểu sơ, Thuộc lòng, Nghiên cứu, Hiểu rõ"})
mapArray:push({ id = 871, color = "#000000", describe = "5 vị trí có thể nghiên cứu nhiều lần, mỗi lần nghiên cứu 100% tăng t.tính cố định tương ứng"})
mapArray:push({ id = 872, color = "#000000", describe = "5 vị trí đều đạt Nghiên cứu, mỗi lần nghiên cứu đều tăng % toàn bộ t.tính Thiên Thư"})
mapArray:push({ id = 873, color = "#000000", describe = "2 Đọc qua tăng 1 Lỗ Đá Thiên Thư"})
mapArray:push({ id = 874, color = "#000000", describe = "3 Hiểu sơ, t.tính cơ bản +5%"})
mapArray:push({ id = 875, color = "#000000", describe = "2 Thuộc lòng, t.tính cơ bản +10%"})
mapArray:push({ id = 876, color = "#000000", describe = "3 Thuộc lòng, t.tính cơ bản +15%"})
mapArray:push({ id = 877, color = "#000000", describe = "1 Nghiên cứu, t.tính chính của Thiên Thư +10%"})
mapArray:push({ id = 878, color = "#000000", describe = "2 Nghiên cứu, t.tính cơ bản +20%"})
mapArray:push({ id = 879, color = "#000000", describe = "3 Nghiên cứu, t.tính chính của Thiên Thư +20%"})
mapArray:push({ id = 880, color = "#000000", describe = "4 Nghiên cứu, t.tính cơ bản +25%"})
mapArray:push({ id = 881, color = "#000000", describe = "5 Nghiên cứu, t.tính chính của Thiên Thư +35%"})
mapArray:push({ id = 882, color = "#000000", describe = "3 Hiểu rõ, t.tính cơ bản +30%"})
mapArray:push({ id = 883, color = "#000000", describe = "5 Hiểu rõ, t.tính chính của Thiên Thư +40%"})
mapArray:push({ id = 884, color = "#000000", describe = "3 Tinh thông, t.tính cơ bản +35%"})
mapArray:push({ id = 885, color = "#000000", describe = "5 Tinh thông, t.tính chính của Thiên Thư +45%"})
mapArray:push({ id = 890, color = "#000000", describe = "Chỉ Thiên Thư Thiện Bản trở lên mới được đổi luyện cùng phẩm chất"})
mapArray:push({ id = 891, color = "#000000", describe = "Toàn bộ trưởng thành của 2 Thiên Thư sẽ được đổi trọn vẹn"})
mapArray:push({ id = 892, color = "#000000", describe = "Tinh Yếu đã khảm ở tầng hiện tại của 2 Thiên Thư cùng Chiến Tích và Đồng khảm Tinh Yếu sẽ trả về túi"})
mapArray:push({ id = 893, color = "#000000", describe = "Trả toàn bộ đá khảm trên 2 Thiên Thư về túi"})
mapArray:push({ id = 910, color = "#000000", describe = "Kỳ Trận trở lên mới được đổi luyện cùng phẩm chất"})
mapArray:push({ id = 911, color = "#000000", describe = "Khi đổi thường, ngoài cấp đột phá và vị trí thuộc tính, toàn bộ trưởng thành của 2 Thiên Thư đều sẽ được đổi trọn vẹn"})
mapArray:push({ id = 912, color = "#000000", describe = "Khi đổi cao cấp, toàn bộ trưởng thành của 2 Thiên Thư đều được đổi trọn vẹn"})
mapArray:push({ id = 913, color = "#000000", describe = "Đổi cao cấp tiêu hao mảnh trận pháp của bên có cấp sao thấp hơn, cấp sao trận pháp chênh lệch càng lớn, cần càng nhiều mảnh trận pháp"})
mapArray:push({ id = 914, color = "#000000", describe = "Nếu cấp cường hóa sau khi đổi vượt giới hạn cấp cường hóa trận pháp hiện tại, phần thừa sẽ chuyển thành nguyên liệu nâng cấp và trả lại"})
mapArray:push({ id = 930, color = "#000000", describe = "Chỉ Thiên Thư Thiện Bản trở lên mới được đổi luyện cùng phẩm chất"})
mapArray:push({ id = 931, color = "#000000", describe = "Toàn bộ trưởng thành của 2 Thiên Thư sẽ được đổi trọn vẹn"})
mapArray:push({ id = 932, color = "#000000", describe = "Tinh Yếu đã khảm ở tầng hiện tại của 2 Thiên Thư cùng Chiến Tích và Đồng khảm Tinh Yếu sẽ trả về túi"})
mapArray:push({ id = 950, color = "#000000", describe = "00:00:00 hàng ngày cài lại XH chiến lực trong Danh Nhân Đường, chỉ hiện Top 50 của cụm liên server"})
mapArray:push({ id = 951, color = "#000000", describe = "00:00:00 - 00:10:00 hàng ngày đóng và cài lại Danh Nhân Đường"})
mapArray:push({ id = 952, color = "#000000", describe = "Quỳ bái tướng trong Danh Nhân Đường được thưởng, tướng cứ được quỳ bái 50 lần cũng được nhận thưởng"})
mapArray:push({ id = 953, color = "#000000", describe = "7 ngày không online, ở lần tổng kết sau sẽ không được vào Danh Nhân Đường cho đến khi online lại"})
mapArray:push({ id = 970, color = "#000000", describe = "Lôi Đài Vương Giả dùng cơ chế 3 người tổ đội giao chiến. Đầu, giữa, cuối lần lượt giao chiến 3 lần theo cơ chế 3 trận thắng 2"})
mapArray:push({ id = 971, color = "#000000", describe = "Thứ 2 hàng tuần mở Lôi Đài Vương Giả. Báo danh: 10:00-19: 00; Đấu Điểm: 19: 00-20:00; Cược: 20:00-20: 30; Giao chiến Bá Chủ: 20: 30-21: 00"})
mapArray:push({ id = 972, color = "#000000", describe = "Đội Top 1 Đấu Điểm được giao chiến với Bá Chủ, người chiến thắng trở thành Bá Chủ mới"})
mapArray:push({ id = 973, color = "#000000", describe = "Đội Bá Chủ lần trước tự động báo danh và vào thẳng vòng chung kết"})
mapArray:push({ id = 974, color = "#000000", describe = "Sau chung kết, thắng nhận thưởng Bá Chủ, thua nhận thưởng Top 1"})
mapArray:push({ id = 975, color = "#000000", describe = "Ghép ngẫu nhiên có thể gặp với người cùng server, sau khi ghép không thể thoát đội và loại thành viên. Đội đủ người sẽ tự động báo danh, sự kiện kết thúc đội tự động giải tán."})
mapArray:push({ id = 976, color = "#000000", describe = "Sau khi tạo đội có thể mời bạn bè vào đội, kết thúc sự kiện đội vẫn được giữ nguyên."})
mapArray:push({ id = 977, color = "#000000", describe = "Sau khi đủ người, 1 thành viên báo danh được coi là cả đội báo danh, báo danh xong không thể thoát đội và loại thành viên."})
mapArray:push({ id = 978, color = "#000000", describe = "Không trong thời gian sự kiện cũng có thể tạo đội, mời thành viên."})
mapArray:push({ id = 979, color = "#000000", describe = "2 đội vào chung kết có thể cổ vũ thành viên, lượt cổ vũ tối đa của 3 thành viên cộng lại là 30."})
mapArray:push({ id = 980, color = "#000000", describe = "Bá Chủ mỗi lần nạp 5000 KNB sẽ phát lì xì 10 KNB cho người online trong toàn cụm liên server, có 1 người nhận lì xì Bá Chủ sẽ nhận lại 5 KNB."})
mapArray:push({ id = 981, color = "#000000", describe = "Thư gửi vào 24:00 mỗi ngày, nếu lì xì phát sau 22:00 trong ngày thì thư gửi vào 24:00 hôm sau"})
mapArray:push({ id = 990, color = "#000000", describe = "Mỗi lần được mời 1 tướng tiến lên, mời cần dùng KNB hoặc lệnh bài tương ứng"})
mapArray:push({ id = 991, color = "#000000", describe = "Cự ly tiến lên mỗi lần là giá trị ngẫu nhiên trong phạm vi nhất định, trên đường tiến lên có thể nhận thưởng rương"})
mapArray:push({ id = 992, color = "#000000", describe = "Sự kiện kết thúc sẽ cài lại cự ly tiến lên"})
mapArray:push({ id = 1010, color = "#000000", describe = "Được dùng Thẻ Ngộ Tâm để lĩnh hội Thiên Thư"})
mapArray:push({ id = 1011, color = "#000000", describe = "Thuộc tính lĩnh hội ra mỗi lần là ngẫu nhiên, có thể tự chọn hoặc thay thế thuộc tính hiện tại"})
mapArray:push({ id = 1012, color = "#000000", describe = "Lĩnh hội có 5 bậc, điều kiện mở mỗi bậc khác nhau nhưng đều có thể mở khóa thông qua tổng lượt lĩnh hội"})
mapArray:push({ id = 1013, color = "#000000", describe = "Giới hạn thuộc tính lĩnh hội mỗi bậc ngày càng cao"})
mapArray:push({ id = 1014, color = "#000000", describe = "Mỗi thuộc tính theo giá trị cao thấp chia thành 5 phẩm chất: Bình thường, Nghiên cứu, Thấu hiểu, Thành thục, Tinh thông"})
mapArray:push({ id = 1015, color = "#000000", describe = "Khi lĩnh hội thuộc tính đạt phẩm chất chỉ định và điều kiện số lượng, sẽ tăng thuộc tính đặc biệt"})
mapArray:push({ id = 1030, color = "#000000", describe = "Có thể tổ đội 3 người để thách đấu chương"})
mapArray:push({ id = 1031, color = "#000000", describe = "Mỗi chương có 9 ải, 3 người được tự chọn ải thách đấu"})
mapArray:push({ id = 1032, color = "#000000", describe = "Thách đấu ải thắng lợi sẽ giảm toàn bộ thuộc tính do mệt mỏi"})
mapArray:push({ id = 1033, color = "#000000", describe = "9 ải đều thách đấu thắng lợi sẽ được coi là vượt ải"})
mapArray:push({ id = 1034, color = "#000000", describe = "Sau khi vượt ải, được chọn thưởng 1 trong 4 thưởng"})
mapArray:push({ id = 1035, color = "#000000", describe = "Được nhận thêm thuộc tính Buff của tướng ra trận theo tiến độ vượt ải"})
mapArray:push({ id = 1050, color = "#000000", describe = "Mỗi lần mua đủ số vật phẩm chỉ định trong Shop này, sẽ được tặng 1 vật phẩm giá thấp nhất trong vòng mua này, vật phẩm gửi qua thư"})
mapArray:push({ id = 1051, color = "#000000", describe = "Đếm mua hoàn lại sẽ dừng và cài lại sau mỗi vòng sự kiện, lịch sử mua chỉ bảo lưu 20 mục gần nhất"})
mapArray:push({ id = 1052, color = "#000000", describe = "Khi số KNB tiêu trong Shop này đạt chỉ định, sẽ được hoàn lại KNB qua thư"})
mapArray:push({ id = 1053, color = "#000000", describe = "Hàng ngày cài lại điều kiện hoàn 100% KNB"})
mapArray:push({ id = 1070, color = "#000000", describe = "Nhấn tham gia mua chung trong cột vật phẩm nào đó, chọn số lượng và thanh toán xong sẽ lập tức tham gia mua chung"})
mapArray:push({ id = 1071, color = "#000000", describe = "Khi mua chung sẽ trừ KNB theo giá gốc, khi tổng kết sẽ dựa vào mốc giảm giá trong lần mua chung này đạt đến để hoàn lại KNB thừa qua thư"})
mapArray:push({ id = 1072, color = "#000000", describe = "Khi tổng số mua chung của vật phẩm nào đó đạt hoặc vượt giá trị dự kiến mua cao nhất thì mua chung thành công và tổng kết vòng mua chung này; Nếu chưa đạt mức cao nhất, thì tổng kết đợt mua chung này vào 00:00:00 hôm sau"})
mapArray:push({ id = 1073, color = "#000000", describe = "Hàng ngày sẽ cài lại nội dung mua chung và trạng thái mua"})
mapArray:push({ id = 1110, color = "#000000", describe = "Tiêu Hành Thiên Hạ báo danh vào 10:00-20:00, áp tiêu vào 20:00-21:00 thứ 6 hàng tuần"})
mapArray:push({ id = 1111, color = "#000000", describe = "Thành viên Bang được chọn vị trí tiêu khác nhau để báo danh bảo vệ, Bang Chủ được điều chỉnh vị trí của người đã báo danh"})
mapArray:push({ id = 1112, color = "#000000", describe = "Bang Chủ được dùng Phồn Vinh Bang nâng cấp tiêu, tăng tốc độ của tiêu"})
mapArray:push({ id = 1113, color = "#000000", describe = "Sau khi bắt đầu áp tiêu, tất cả các Bang cùng xuất phát, cuối cùng xếp hạng theo cự ly di chuyển của tiêu"})
mapArray:push({ id = 1114, color = "#000000", describe = "Thưởng XH sẽ phát qua thư cho toàn bộ thành viên Bang"})
mapArray:push({ id = 1115, color = "#000000", describe = "Sau khi bắt đầu áp tiêu, thành viên các Bang được tự chọn mục tiêu để công"})
mapArray:push({ id = 1116, color = "#000000", describe = "Sau khi bắt đầu áp tiêu, sẽ không thể thay đổi đội hình thủ và vị trí bảo vệ"})
mapArray:push({ id = 1117, color = "#000000", describe = "Hộ Giáp: sau khi đánh bại toàn bộ phe thủ ở vị trí này, mới được công vị trí khác"})
mapArray:push({ id = 1118, color = "#000000", describe = "Cờ Tiêu: sau khi đánh bại toàn bộ phe thủ ở vị trí này, toàn bộ thuộc tính khi thủ của thành viên Bang này -20%"})
mapArray:push({ id = 1119, color = "#000000", describe = "Bánh Xe: sau khi đánh bại toàn bộ phe thủ ở vị trí này, tốc độ tiêu -35%"})
mapArray:push({ id = 1120, color = "#000000", describe = "Toa Xe: sau khi đánh bại toàn bộ phe thủ ở vị trí này, tiêu dừng lại"})
mapArray:push({ id = 1121, color = "#000000", describe = "Chỉ có người đã báo danh mới được thưởng sự kiện"})
mapArray:push({ id = 1130, color = "#000000", describe = "Có thể tự chọn xe để tấn công, cùng lúc chỉ được công 1 xe"})
mapArray:push({ id = 1131, color = "#000000", describe = "Cùng công đánh mục tiêu, toàn bộ thuộc tính +20%, Bang Chủ/Bang Phó được cài mục tiêu cùng công đánh"})
mapArray:push({ id = 1132, color = "#000000", describe = "Điều chỉnh công: có thể điều chỉnh đội hình công và hồi đầy HP cho tướng"})
mapArray:push({ id = 1133, color = "#000000", describe = "Hộ Giáp: sau khi đánh bại toàn bộ phe thủ ở vị trí này, mới được công vị trí khác"})
mapArray:push({ id = 1134, color = "#000000", describe = "Cờ Tiêu: sau khi đánh bại toàn bộ phe thủ ở vị trí này, toàn bộ thuộc tính khi thủ của thành viên Bang này -20%"})
mapArray:push({ id = 1135, color = "#000000", describe = "Bánh Xe: sau khi đánh bại toàn bộ phe thủ ở vị trí này, tốc độ tiêu -35%"})
mapArray:push({ id = 1136, color = "#000000", describe = "Toa Xe: sau khi đánh bại toàn bộ phe thủ ở vị trí này, tiêu dừng lại"})
mapArray:push({ id = 1137, color = "#000000", describe = "Phe thủ có 5 phút hồi sinh, chỉ cần có phe thủ hồi sinh, vị trí này sẽ có hiệu lực lại"})
mapArray:push({ id = 1138, color = "#000000", describe = "Sau khi bắt đầu áp tiêu, sẽ không thể thay đổi đội hình thủ và vị trí bảo vệ"})
mapArray:push({ id = 1139, color = "#000000", describe = "Sự kiện kết thúc, xếp hạng theo cự ly di chuyển của tiêu"})
mapArray:push({ id = 1140, color = "#000000", describe = "Thưởng XH sẽ phát qua thư cho toàn bộ thành viên Bang"})
mapArray:push({ id = 1141, color = "#000000", describe = "Chỉ có người đã báo danh mới được thưởng sự kiện"})
mapArray:push({ id = 1150, color = "#000000", describe = "Thách đấu thắng lợi, số sao +1"})
mapArray:push({ id = 1151, color = "#000000", describe = "Khi giai đoạn hiện tại đạt số sao tối đa, thắng thêm 1 lần sẽ vào giai đoạn sau"})
mapArray:push({ id = 1152, color = "#000000", describe = "Sau khi thách đấu thành công, sẽ làm mới đối thủ vào 24:00 trong ngày"})
mapArray:push({ id = 1153, color = "#000000", describe = "Sau khi chọn đình chiến, sẽ làm mới đối thủ vào 24:00 trong ngày"})
mapArray:push({ id = 1154, color = "#000000", describe = "Theo giai đoạn hiện tại, lượt đình chiến đạt nhất định, số sao -1"})
mapArray:push({ id = 1155, color = "#000000", describe = "Sau khi đạt Đại Sư, sẽ ghi lại tổng số sao và tiến hành xếp hạng"})
mapArray:push({ id = 1156, color = "#000000", describe = "Top 20 giai đoạn Đại Sư là Vương Giả"})
mapArray:push({ id = 1157, color = "#000000", describe = "Sau khi đạt giai đoạn Kim Cương, số người ra trận tăng lên 6"})
mapArray:push({ id = 1158, color = "#000000", describe = "Sau khi đạt giai đoạn Đại Sư, số người ra trận tăng lên 7"})
mapArray:push({ id = 1159, color = "#000000", describe = "24:00 hàng ngày cập nhật Bảng Đấu Hạng và giai đoạn Bá Vương"})
mapArray:push({ id = 1160, color = "#000000", describe = "Mỗi 3 tuần là 1 mùa, 22:00-24:00 CN tuần thứ 3 sẽ tổng kết, 22:30 có thể xem Bảng Đấu Hạng"})
mapArray:push({ id = 1161, color = "#000000", describe = "Mỗi mùa đấu kết thúc, sẽ phát thưởng XH"})
mapArray:push({ id = 1162, color = "#000000", describe = "Mỗi mùa đấu kết thúc, sẽ điều chỉnh giai đoạn, số sao có cài lại thành 1"})
mapArray:push({ id = 1170, color = "#000000", describe = "T.tính Pet: thuộc tính Pet trong chiến đấu, tăng cường độ kỹ năng Pet"})
mapArray:push({ id = 1171, color = "#000000", describe = "Tổng t.tính của tướng ra trận sẽ quy đổi thành t.tính Pet theo tỉ lệ"})
mapArray:push({ id = 1172, color = "#000000", describe = "Mở Thầy Huấn Luyện tăng thuộc tính Pet"})
mapArray:push({ id = 1173, color = "#000000", describe = "Tất cả Pet Chiến đều có thể nâng lên phẩm chất cao nhất"})
mapArray:push({ id = 1174, color = "#000000", describe = "Pet Chiến đột phá đến 5 sao có thể nâng phẩm chất "})
mapArray:push({ id = 1175, color = "#000000", describe = "Nâng phẩm sẽ tăng phẩm chất Pet, tăng thuộc tính ra trận, tăng Buff thuộc tính toàn đội, tăng kỹ năng, cấp sao cài lại là 0"})
mapArray:push({ id = 1190, color = "#000000", describe = "Tất cả Pet đều có thể hoán công"})
mapArray:push({ id = 1191, color = "#000000", describe = "Khi hoán công, cấp sao và phẩm cấp luyện của Pet đều được đổi trọn vẹn"})
mapArray:push({ id = 1192, color = "#000000", describe = "Trước khi hoán công nếu Pet có Thầy Huấn Luyện sau khi hoán công không đủ điều kiện mở Thầy Huấn Luyện thì tự động gỡ Thầy Huấn Luyện"})
mapArray:push({ id = 1193, color = "#000000", describe = "Khi hoán công dùng pet chưa luyện có phẩm cấp tương đối thấp, chênh lệch phẩm cấp giữa Pet đổi càng lớn, tiêu hao càng nhiều"})
mapArray:push({ id = 1194, color = "#000000", describe = "Pet đã luyện và Pet đã ra trận không thể chọn để đổi"})
mapArray:push({ id = 1210, color = "#000000", describe = "Diễn Võ Bang cần Bang đạt Lv3, Bang Chủ không đang nhượng chức hoặc bị luận tội, Bang không trong thời gian giải tán mới mở; Thành viên mới vào Bang ngày thứ 2 mới được tham gia"})
mapArray:push({ id = 1211, color = "#000000", describe = "Giới hạn Trung Nghĩa diễn võ mỗi ngày là 350, không tích lũy điểm Trung Nghĩa khi Bang Chủ/Bang Phó không trong tình trạng bình thường"})
mapArray:push({ id = 1212, color = "#000000", describe = "Khi điểm Trung Nghĩa đạt nhất định sẽ tiêu hao Trung Nghĩa và vào giai đoạn chuẩn bị. Bang Chủ/Bang Phó mới được mở, trong 48 tiếng chưa mở sẽ bị hủy."})
mapArray:push({ id = 1213, color = "#000000", describe = "Mỗi lần diễn võ mặc định mở giai đoạn cao nhất mà Bang được mở lần này, mỗi lần thắng sẽ tăng giai đoạn cao nhất được mở, thua sẽ giảm"})
mapArray:push({ id = 1214, color = "#000000", describe = "Khi chọn mở độ khó thấp hơn giai đoạn cao nhất được mở lần này, giai đoạn cao nhất được mở lần sau sẽ không giảm"})
mapArray:push({ id = 1215, color = "#000000", describe = "Diễn võ trong 30 phút, trong thời gian giới hạn đánh bại Thủ Lĩnh sẽ thắng"})
mapArray:push({ id = 1216, color = "#000000", describe = "Diễn võ chia 4 khu: Thủ Lĩnh, Cánh Trái, Cánh Phải, Trung Quân. Đánh bại Thủ Lĩnh sẽ thắng diễn võ, đánh bại các khu vực khác nhận thuộc tính khác nhau"})
mapArray:push({ id = 1217, color = "#000000", describe = "00:00:00 hàng ngày ngẫu nhiên cài lại 1 lần thuộc tính thêm của Cánh Trái và Cánh Phải khi mở Diễn Võ Bang trong ngày"})
mapArray:push({ id = 1218, color = "#000000", describe = "Ngoài Trung Quân, mỗi người mỗi lần gây s.thương cho 3 khu vực khác sẽ có bảo vệ s.thương, phần thừa không tính"})
mapArray:push({ id = 1219, color = "#000000", describe = "Cánh Trái và Cánh Phải sau khi bị công phá sẽ hồi sinh sau 1 thời gian, Trung Quân sẽ hồi sinh ngay sau khi bị công phá"})
mapArray:push({ id = 1220, color = "#000000", describe = "Mỗi lần công đều có CD, hãy sắp xếp hợp lý thứ tự và mục tiêu mỗi lần công"})
mapArray:push({ id = 1221, color = "#000000", describe = "Bang Chủ có thể triệu tập thành viên offline 3 ngày trợ chiến, 10 phút sau khi mở diễn võ những người này công khu vực chỉ định, nhưng thuộc tính giảm 1/2"})
mapArray:push({ id = 1222, color = "#000000", describe = "Cứ tham gia là được nhận thưởng, thưởng phát vào 23:59:59 cùng ngày, nếu đánh bại vào sau 22:00 hôm sau phát"})
mapArray:push({ id = 1230, color = "#000000", describe = "Giới hạn Trung Nghĩa mỗi ngày là 250."})
mapArray:push({ id = 1231, color = "#000000", describe = "Sau khi Trung Nghĩa đạt giới hạn vẫn có thể lễ bái, nhận Phồn Vinh Bang, Exp Bang và cống hiến cá nhân."})
mapArray:push({ id = 1250, color = "#000000", describe = "Hàng ngày chỉ được yêu cầu người khác tặng 1 vật phẩm"})
mapArray:push({ id = 1251, color = "#000000", describe = "Không giới hạn số vật phẩm tặng cho người khác trong ngày"})
mapArray:push({ id = 1252, color = "#000000", describe = "Tặng vật phẩm nhận điểm Hiệp Nghĩa, không giới hạn số điểm nhận"})
mapArray:push({ id = 1253, color = "#000000", describe = "Nhận vật phẩm được tặng từ ngày hôm trước xong mới được yêu cầu xin tặng của ngày hôm sau"})
mapArray:push({ id = 1254, color = "#000000", describe = "Khi rời Bang, không bảo lưu trạng thái nhận vật phẩm hiện tại"})
mapArray:push({ id = 1270, color = "#000000", describe = "Mỗi lần chú giải có thể kích hoạt thuộc tính chú giải tương ứng"})
mapArray:push({ id = 1271, color = "#000000", describe = "Sau khi tất cả các mục của chương hiện tại được chú giải hết có thể vào chương sau qua Tổng Quan"})
mapArray:push({ id = 1272, color = "#000000", describe = "Thiên Thư 4 trở lên sau khi đeo Mật Yếu có thể kích hoạt kỹ năng của Mật Yếu này, tướng ra trận trang bị Thiên Thư khi chiến đấu sẽ có kỹ năng này"})
mapArray:push({ id = 1273, color = "#000000", describe = "Hiệu quả kỹ năng Mật Yếu được Buff chú giải, chương chú giải hiện tại càng cao thì hiệu quả kỹ năng Mật Yếu càng mạnh"})
mapArray:push({ id = 1274, color = "#000000", describe = "Sau khi gỡ Mật Yếu, kỹ năng Mật Yếu của Thiên Thư vô hiệu, đồng thời Mật Yếu này cũng không được nhận thêm Buff chú giải"})
mapArray:push({ id = 1275, color = "#000000", describe = "Thuộc tính và cấp chú giải được đổi trọn vẹn"})
mapArray:push({ id = 1290, color = "#000000", describe = "Nâng bậc Mật Yếu chỉ định cần dùng mảnh Mật Yếu này"})
mapArray:push({ id = 1291, color = "#000000", describe = "Hiệu quả kỹ năng Mật Yếu mạnh lên theo bậc của Mật Yếu này"})
mapArray:push({ id = 1330, color = "#000000", describe = "Trước khi cầu nguyện cần chọn tổng thưởng và chọn nội dung thưởng trong giao diện."})
mapArray:push({ id = 1331, color = "#000000", describe = "Cực phẩm được chọn 3, tinh phẩm được chọn 5. Nếu tổng thưởng chưa chọn đủ sẽ không thể cầu nguyện."})
mapArray:push({ id = 1332, color = "#000000", describe = "Chọn xong tổng thưởng có thể dùng đạo cụ tương ứng nhấn nút cầu nguyện, nhận thưởng ngẫu nhiên trong tổng thưởng đã chọn."})
mapArray:push({ id = 1350, color = "#000000", describe = "Thuần hóa gồm 6 phẩm chất: Hung Dữ, Hiền Lành, Dễ Gần, Quấn Quýt, Linh Tính, Trung Thành. Mỗi lần thuần hóa chỉ ngẫu nhiên chia lại thuộc tính giữa cấp này và cấp sau, mỗi lần thuần hóa tối thiểu +1 cấp, chắc chắn tăng thuộc tính"})
mapArray:push({ id = 1351, color = "#000000", describe = "Cấp tương ứng với phẩm chất: Hung Dữ (1-12), Hiền Lành (13-30), Dễ Gần (31-55), Quấn Quýt (56-80), Linh Tính (81-150), Trung Thành (151-200)"})
mapArray:push({ id = 1352, color = "#000000", describe = "Tỉ lệ thuần hóa thêm chỉ ảnh hưởng thuộc tính thuần hóa thêm"})
mapArray:push({ id = 1353, color = "#000000", describe = "3 Hung Dữ, toàn đội HP +5000, võ lực +1000, nội lực +1000, thủ +1000, thân pháp +1000"})
mapArray:push({ id = 1354, color = "#000000", describe = "4 Hung Dữ, Pet: võ lực +1%, nội lực +1%"})
mapArray:push({ id = 1355, color = "#000000", describe = "5 Hung Dữ, tất cả t.tính toàn đội +3%"})
mapArray:push({ id = 1356, color = "#000000", describe = "2 Hiền Lành, toàn đội HP +15000, võ lực +3000, nội lực +3000, thủ +3000, thân pháp +3000"})
mapArray:push({ id = 1357, color = "#000000", describe = "4 Hiền Lành, Pet: võ lực +3%, nội lực +3%"})
mapArray:push({ id = 1358, color = "#000000", describe = "5 Hiền Lành, tất cả t.tính toàn đội +8%"})
mapArray:push({ id = 1359, color = "#000000", describe = "2 Dễ Gần, toàn đội HP +25000, võ lực +5000, nội lực +5000, thủ +5000, thân pháp +5000"})
mapArray:push({ id = 1360, color = "#000000", describe = "4 Dễ Gần, Pet: võ lực +5%, nội lực +5%"})
mapArray:push({ id = 1361, color = "#000000", describe = "5 Dễ Gần, tất cả t.tính toàn đội +12%"})
mapArray:push({ id = 1362, color = "#000000", describe = "3 Quấn Quýt, toàn đội HP +50000, võ lực +10000, nội lực +10000, thủ +10000, thân pháp +10000"})
mapArray:push({ id = 1363, color = "#000000", describe = "4 Quấn Quýt, Pet: võ lực +8%, nội lực +8%"})
mapArray:push({ id = 1364, color = "#000000", describe = "5 Quấn Quýt, tất cả t.tính toàn đội +20%"})
mapArray:push({ id = 1365, color = "#000000", describe = "3 Linh Tính, toàn đội HP +100000, võ lực +20000, nội lực +20000, thủ +20000, thân pháp +20000"})
mapArray:push({ id = 1366, color = "#000000", describe = "4 Linh Tính, Pet: Võ lực +12%, nội lực +12%"})
mapArray:push({ id = 1367, color = "#000000", describe = "5 Linh Tính, tất cả t.tính toàn đội +30%"})
mapArray:push({ id = 13681, color = "#000000", describe = "3 Trung Thành , toàn đội HP +200000, võ lực +40000, nội lực +40000, thủ +40000, thân pháp +40000"})
mapArray:push({ id = 13691, color = "#000000", describe = "4 Trung Thành, Pet: Võ lực +18%, nội lực +18%"})
mapArray:push({ id = 13701, color = "#000000", describe = "5 Trung Thành, tất cả t.tính toàn đội +40%"})
mapArray:push({ id = 1368, color = "#000000", describe = "Võ Lâm Công Địch do toàn bộ người trong cụm liên server cùng thách đấu"})
mapArray:push({ id = 1369, color = "#000000", describe = "Võ Lâm Công Địch mở vào 12:00-13:00 thứ 7, CN hàng tuần"})
mapArray:push({ id = 1370, color = "#000000", describe = "Võ Lâm Công Địch thách đấu tối đa duy trì 5 hiệp"})
mapArray:push({ id = 1371, color = "#000000", describe = "Trong sự kiện, nếu thách đấu thành công sẽ tăng cấp Võ Lâm Công Địch lần sau; thất bại sẽ giảm cấp"})
mapArray:push({ id = 1372, color = "#000000", describe = "Trong sự kiện, nếu thách đấu thành công, tất cả mọi người được thưởng Phá Rương"})
mapArray:push({ id = 1373, color = "#000000", describe = "Khi Võ Lâm Công Địch bị công phá, chờ người đang đánh đánh xong, s.thương cũng sẽ tính vào BXH"})
mapArray:push({ id = 1374, color = "#000000", describe = "Sự kiện kết thúc được 30 phút sẽ gửi thưởng XH sát thương qua thư"})
mapArray:push({ id = 1375, color = "#000000", describe = "Do Võ Lâm Công Địch quá mạnh, không chỉ miễn hầu hết trạng thái debuff, mà còn miễn hút nộ"})
mapArray:push({ id = 1385, color = "#000000", describe = "Mỗi rương mỗi người chỉ được đào 1 lần/ngày"})
mapArray:push({ id = 1386, color = "#000000", describe = "Khi vị trí dừng hiện tại gần kho báu có thể đào, sẽ hiện thông báo"})
mapArray:push({ id = 1387, color = "#000000", describe = "00:00 mỗi ngày sẽ cài lại lượt được đào"})
mapArray:push({ id = 1390, color = "#000000", describe = "Trong trạng thái chôn báu vật, có thể chôn rương đã chọn ở khu vực bất kỳ trong map"})
mapArray:push({ id = 1391, color = "#000000", describe = "Có nhiều loại vật phẩm trong mỗi rương và chắc chắn có 1 thưởng cao nhất"})
mapArray:push({ id = 1392, color = "#000000", describe = "Mỗi rương mỗi người chỉ được nhận 1 lần, vật phẩm nhận là ngẫu nhiên"})
mapArray:push({ id = 1393, color = "#000000", describe = "Rương sẽ biến mất sau khi nhận xong hoặc chôn đủ 24 tiếng"})
mapArray:push({ id = 1410, color = "#000000", describe = "Khi luyện Tâm Pháp cần Xu Chu Tâm và bản thể không luyện của Tâm Pháp này, lượng tiêu hao tăng theo tiến độ luyện"})
mapArray:push({ id = 1411, color = "#000000", describe = "Tâm Pháp đột phá đến mức nhất định sẽ kích hoạt hiệu quả đặc biệt tương ứng của Tâm Pháp này, hiệu quả này chỉ có tác dụng cho tướng đeo Tâm Pháp này"})
mapArray:push({ id = 1412, color = "#000000", describe = "Ghép Tâm Pháp cần mảnh Tâm Pháp tương ứng, mỗi loại 1 mảnh. Mỗi loại Tâm Pháp cần số loại mảnh Tâm Pháp tương ứng"})
mapArray:push({ id = 1413, color = "#000000", describe = "Bán Tâm Pháp sẽ dựa vào tiến độ luyện hiện tại để hoàn Xu Chu Tâm theo tỉ lệ 3/4"})
mapArray:push({ id = 1430, color = "#000000", describe = "Ân Cừu Lục mở vào 10:00-22:00 mỗi thứ 3, 5, 7"})
mapArray:push({ id = 1431, color = "#000000", describe = "Lệnh Theo Dõi để tham gia Ân Cừu Lục cài lại vào 00:00 mỗi thứ 3, 5, 7"})
mapArray:push({ id = 1432, color = "#000000", describe = "Trong Ân Cừu Lục, sở hữu tối thiểu 1 mảnh tâm pháp mới được tham gia tranh đoạt tâm pháp tương ứng"})
mapArray:push({ id = 1433, color = "#000000", describe = "Khi chọn mảnh Tâm Pháp để tranh đoạt không chỉ cướp được mảnh, còn có thể cướp được cả Xu Chu Tâm của đối thủ"})
mapArray:push({ id = 1434, color = "#000000", describe = "Cướp thắng sẽ chắc chắn cướp được Xu Chu Tâm của đối thủ, tỷ lệ nhất định cướp được mảnh tâm pháp đối thủ có, khi cướp tiêu hao thể lực càng cao tỷ lệ cướp được mảnh càng lớn"})
mapArray:push({ id = 1435, color = "#000000", describe = "Sau khi bị cướp có thời gian miễn chiến, trong thời gian đó không thể bị công, cũng không thể bị tìm thấy. Dùng thẻ miễn chiến cũng có thể chủ động miễn chiến. Chủ động công người khác hoặc tổ đội sẽ kết thúc miễn chiến"})
mapArray:push({ id = 1436, color = "#000000", describe = "Khi cướp mảnh có thể chọn tổ đội, xác suất cướp và lượng cướp được Xu Chu Tâm sẽ tăng. Mỗi thành viên tối đa nhận 20 lần thưởng hỗ trợ/ngày"})
mapArray:push({ id = 1437, color = "#000000", describe = "Khi tổ đội, thể lực thành viên dùng sẽ do đội trưởng chịu. Nếu thành viên cướp thành công, đội trưởng nhận mảnh và Xu Chu Tâm cướp được, thành viên chỉ nhận thêm 1 phần Xu Chu Tâm do lần này cướp được và có xác suất nhận rương mảnh Tâm Pháp phẩm tương ứng"})
mapArray:push({ id = 1438, color = "#000000", describe = "Khi phản kích người cướp, nếu thắng sẽ chắc chắn đoạt lại mảnh bị cướp, nếu trên người đối phương không có mảnh đó sẽ cướp Xu Chu Tâm để đền bù."})
mapArray:push({ id = 1439, color = "#000000", describe = "Lv75 trở xuống khi cướp mảnh có thể chủ động tìm được toàn bộ người sở hữu, không bị người Lv75 trở lên chủ động tìm được"})
mapArray:push({ id = 1450, color = "#000000", describe = "Trung Nghĩa trong ngày đạt 120, 250; Bang Chủ hoặc Bang Phó sẽ phát lì xì sôi nổi 1000 KNB"})
mapArray:push({ id = 1451, color = "#000000", describe = "Bang tối thiểu cần có 5 người để phát lì xì sôi nổi, tối đa 30 người nhận"})
mapArray:push({ id = 1452, color = "#000000", describe = "Chỉ được phát lì xì sôi nổi sau 20:00 trong ngày, lì xì chưa phát sẽ hết hiệu lực vào 00:00"})
mapArray:push({ id = 1453, color = "#000000", describe = "Thời gian nhận lì xì sôi nổi là 30 phút, lì xì hết giờ chưa nhận sẽ vô hiệu"})
mapArray:push({ id = 1470, color = "#000000", describe = "Tâm Pháp tím trở lên mới được khảm đá"})
mapArray:push({ id = 1471, color = "#000000", describe = "Huyền Quan Tâm Pháp chỉ được khảm đá thuộc tính cơ bản, không thể khảm đá thuộc tính kèm"})
mapArray:push({ id = 1472, color = "#000000", describe = "Cấp đá Tâm Pháp được khảm phụ thuộc Huyền Quan, cấp Huyền Quan càng cao, cấp đá khảm càng cao"})
mapArray:push({ id = 1490, color = "#000000", describe = "Tâm Pháp tím trở lên mới được ngưng luyện Huyền Quan"})
mapArray:push({ id = 1491, color = "#000000", describe = "Mỗi quyển Tâm Pháp có 5 Huyền Quan, lần lượt tăng 5 loại thuộc tính là HP, võ lực, thủ, nội lực, thân pháp. Huyền Quan có thể ngưng luyện nhiều lần và nhất định tăng thuộc tính"})
mapArray:push({ id = 1492, color = "#000000", describe = "Tâm Pháp mặc định mở Huyền Quan thứ 1, khi Huyền Quan trước ngưng luyện đạt cấp nhất định sẽ tự động mở Huyền Quan tiếp theo"})
mapArray:push({ id = 1493, color = "#000000", describe = "Khi thuộc tính của đá khảm và Huyền Quan giống nhau, kích hoạt hiệu quả “Tương Phù”, thuộc tính của đá và Huyền Quan tương ứng +50%"})
mapArray:push({ id = 1494, color = "#000000", describe = "Khi thuộc tính của đá khảm và Huyền Quan phụ giống nhau, kích hoạt hiệu quả “Tương Sinh”, thuộc tính của đá và Huyền Quan tương ứng +30%"})
mapArray:push({ id = 1495, color = "#000000", describe = "Khi 5 Huyền Quan luyện đến mức nhất định có thể kích hoạt thuộc tính kèm"})
mapArray:push({ id = 1510, color = "#000000", describe = "Thời hạn mua Thẻ Vàng Chí Tôn là 7 ngày, mua xong được nhận thưởng Thẻ Vàng liên tiếp 7 ngày"})
mapArray:push({ id = 1511, color = "#000000", describe = "Số vật phẩm thưởng cụ thể thay đổi theo trạng thái nhận lúc đó, cấp/XH khi nhận càng cao, thưởng Thẻ Vàng càng nhiều"})
mapArray:push({ id = 1512, color = "#000000", describe = "Thưởng Thẻ Vàng trong ngày chưa nhận sẽ gửi qua thư vào 23:59:59 cùng ngày"})
mapArray:push({ id = 1513, color = "#000000", describe = "Thưởng XH Quần Hào Phổ phụ thuộc XH Quần Hào Phổ khi nhận thưởng, XH càng cao thưởng Thẻ Vàng càng nhiều. Xếp hạng 1 nhận nhiều nhất, sau đó giảm dần, tối thiểu là 1"})
mapArray:push({ id = 1530, color = "#000000", describe = "Tâm Pháp tím trở lên mới được đổi luyện cùng phẩm chất"})
mapArray:push({ id = 1531, color = "#000000", describe = "Toàn bộ trưởng thành của 2 Tâm Pháp sẽ được đổi trọn vẹn"})
mapArray:push({ id = 1532, color = "#000000", describe = "Cấp đột phá của 2 Tâm Pháp chênh càng lớn, Xu Chu Tâm tiêu khi đổi càng nhiều"})
mapArray:push({ id = 1550, color = "#000000", describe = "Mỗi người mỗi ngày được đuổi 3 Niên Thú làm mới trong lãnh địa của mình, 3 Niên Thú người khác đuổi đến, đuổi Niên Thú người khác đuổi về không mất lượt"})
mapArray:push({ id = 1551, color = "#000000", describe = "Mỗi lần đuổi Niên Thú sẽ rớt số KNB ngẫu nhiên, click để nhặt"})
mapArray:push({ id = 1552, color = "#000000", describe = "Mỗi Niên Thú sau khi bị đuổi lần 1 sẽ sang lãnh địa của 1 thành viên sôi nổi bất kỳ, nếu người này đuổi được Niên Thú trong thời gian chỉ định, Niên Thú sẽ bị đuổi về nơi làm mới ban đầu, và có thể xua đuổi tiếp, KNB rớt cũng tăng"})
mapArray:push({ id = 1553, color = "#000000", describe = "1 Niên Thú bị đuổi 3 lần sẽ biến mất"})
mapArray:push({ id = 1570, color = "#000000", describe = "Server đã mở tính năng liên server mới được tham gia Anh Hùng Đại Hội, khi mở Anh Hùng Đại Hội, từ Lv60 trở lên mặc định báo danh tham gia"})
mapArray:push({ id = 1571, color = "#000000", describe = "Anh Hùng Đại Hội mỗi tuần chia 2 mùa đấu, thứ 3-6 là đấu Anh Hào, thứ 7-2 là đấu Tuấn Kiệt, mở vào 10:00~22:00 mỗi ngày"})
mapArray:push({ id = 1572, color = "#000000", describe = "Người tham gia được chia ngẫu nhiên vào 4 cụm (Đông Hoa, Giang Nam, Tây Xuyên, Sóc Bắc), có thể công lẫn nhau và nhận điểm. Khi mùa đấu kết thúc lấy điểm cuối cùng để xếp hạng. Mùa mới bắt đầu sẽ cài lại XH"})
mapArray:push({ id = 1573, color = "#000000", describe = "XH mỗi cụm độc lập nhau (VD: Mỗi cụm đều có 1 hạng 1), người được hiển thị công khai cuối cùng là người có tổng điểm cao nhất toàn server"})
mapArray:push({ id = 1574, color = "#000000", describe = "Điểm Anh Hùng ban đầu của mỗi người là 1000, mỗi lần chiến đấu sẽ dựa vào XH đối thủ thách đấu và thắng thua quyết định số điểm nhận hoặc trừ, mỗi người tối thiểu là 200 điểm"})
mapArray:push({ id = 1575, color = "#000000", describe = "Khi chọn đối thủ có thể thách đấu người cụm khác, nhưng toàn bộ điểm nhận được chỉ dùng để xếp hạng trong cụm của mình"})
mapArray:push({ id = 1576, color = "#000000", describe = "Mỗi lần đánh thắng được nhận điểm, thua trừ điểm. Bất luận thắng thua đều được Danh Vọng dùng mua đạo cụ luyện trong Shop Danh Vọng"})
mapArray:push({ id = 1577, color = "#000000", describe = "22:00 hàng ngày tổng kết 1 lần thưởng theo XH, và gửi qua thư cho toàn bộ những người tối thiểu tham gia 1 trận trong mùa hiện tại"})
mapArray:push({ id = 1578, color = "#000000", describe = "Hàng ngày có thể lĩnh thưởng tổng kết theo XH được tính từ hôm trước, thưởng và trạng thái nhận sẽ cài lại khi bắt đầu mùa mới"})
mapArray:push({ id = 1579, color = "#000000", describe = "Hàng ngày có thể dựa vào XH hiện tại của bản thân nhận chiết khấu tương ứng khi dùng Danh Vọng để đổi đạo cụ luyện trong giao diện Đổi Ưu Đãi"})
mapArray:push({ id = 1580, color = "#000000", describe = "Tất cả những người tham gia tối thiểu 1 trận đều được tính vào BXH Bang, khi tổng kết mỗi mùa sẽ dựa theo XH tổng điểm của Bang để gửi thưởng cho thành viên tham gia Anh Hùng Đại Hội qua thư"})
mapArray:push({ id = 1590, color = "#000000", describe = "10:00-22:00 hàng ngày từ 9.2-23.2 mở Đánh Niên Thú"})
mapArray:push({ id = 1591, color = "#000000", describe = "Nhấn icon pháo phía dưới màn hình để công Niên Thú, pháo khác nhau gây sát thương khác nhau"})
mapArray:push({ id = 1592, color = "#000000", describe = "Công Niên Thú có xác suất rớt thưởng, nhấn thưởng rớt có thể nhặt "})
mapArray:push({ id = 1593, color = "#000000", describe = "Mỗi lần Niên Thú bị đánh chạy sẽ gửi 1 lần thưởng đánh bại cho toàn server và 60 giây sau Niên Thú sẽ tái xuất hiện"})
mapArray:push({ id = 1594, color = "#000000", describe = "Mỗi lần công Niên Thú sẽ được điểm tương ứng với pháo, 22:00 hàng ngày sẽ phát thưởng XH điểm"})
mapArray:push({ id = 1600, color = "#000000", describe = "Minh Tâm gồm 5 phẩm cấp Mê Đồ, Soi Sáng, Giác Ngộ, Quán Đỉnh, Thiên Nhất"})
mapArray:push({ id = 1601, color = "#000000", describe = "5 vị trí có thể luyện nhiều lần, mỗi lần luyện chắc chắn tăng t.tính cố định tương ứng"})
mapArray:push({ id = 1602, color = "#000000", describe = "5 vị trí đều đạt Thiên Nhất, mỗi lần luyện đều tăng % toàn bộ t.tính Tâm Pháp"})
mapArray:push({ id = 1603, color = "#000000", describe = "Khi tiến độ luyện của 5 vị trí đạt điều kiện nhất định sẽ tăng thêm % t.tính chính của Tâm Pháp, % toàn bộ t.tính Tâm Pháp, % t.tính Đá Tâm Pháp và sức mạnh đặc biệt của Tâm Pháp. Minh Tâm luyện càng cao, t.tính tăng thêm càng nhiều"})
mapArray:push({ id = 1604, color = "#000000", describe = "Khi đổi luyện Minh Tâm của Tâm Pháp cũng sẽ đổi toàn bộ"})
mapArray:push({ id = 1611, color = "#000000", describe = "Mỗi ngày tối đa được luyện hóa 8 lần."})
mapArray:push({ id = 1612, color = "#000000", describe = "Luyện hóa có thể nâng phẩm cấp thấp lên cấp cao."})
mapArray:push({ id = 1613, color = "#000000", describe = "Mỗi khi tăng 1 cấp Bang, thời gian luyện hóa giảm 30 phút."})
mapArray:push({ id = 1614, color = "#000000", describe = "Thành viên Bang có thể hỗ trợ nhau, mỗi lần hỗ trợ, luyện hóa giảm 1 tiếng."})
mapArray:push({ id = 1615, color = "#000000", describe = "Mỗi thành viên có 5 lượt hỗ trợ trong ngày, mỗi lần hỗ trợ nhận 20 KNB."})
mapArray:push({ id = 1616, color = "#000000", describe = "Cùng 1 vật phẩm luyện hóa chỉ được hỗ trợ 1 lần, không giới hạn lượt vật phẩm được hỗ trợ."})
mapArray:push({ id = 1617, color = "#000000", describe = "Không thể hỗ trợ luyện hóa vật phẩm của bản thân."})
mapArray:push({ id = 1618, color = "#000000", describe = "Mỗi lần hỗ trợ có 10% xác suất hoàn thành luyện hóa vật phẩm này ngay, người hỗ trợ nhận thêm 100 KNB."})
mapArray:push({ id = 1625, color = "#000000", describe = "Luận tội cần tiêu 500 KNB. Trong 24 tiếng, thành công thì người luận tội trở thành Bang Chủ mới và không hoàn lại KNB. Thất bại hoàn lại 250 KNB."})
mapArray:push({ id = 1626, color = "#000000", describe = "Thông tin luận tội sẽ gửi cho toàn bộ thành viên sôi nổi trong Bang để bỏ phiếu (Bang Chủ hiện tại & người luận tội không được bỏ phiếu), trên 75% tán thành sẽ luận tội thành công."})
mapArray:push({ id = 1627, color = "#000000", describe = "Bỏ phiếu theo hình thức giấu tên, gửi kết quả cho toàn bộ thành viên qua thư."})
mapArray:push({ id = 1630, color = "#000000", describe = "Tướng Tông Sư (Tím) trở lên được khảm Thiên Mệnh."})
mapArray:push({ id = 1631, color = "#000000", describe = "Mỗi tướng được khảm 9 Thiên Mệnh, 3 hình vuông, 3 hình tròn, 3 hình tam giác."})
mapArray:push({ id = 1632, color = "#000000", describe = "Tướng không được khảm Thiên Mệnh cùng loại."})
mapArray:push({ id = 1633, color = "#000000", describe = "Thiên Mệnh có thể thôn tính để nhận Exp đi nâng cấp, khi thôn tính nhận toàn bộ Exp."})
mapArray:push({ id = 1634, color = "#000000", describe = "Thiên Mệnh có thể tách thành Tinh Phách, dùng mua vật phẩm trong Shop Tinh Phách."})
mapArray:push({ id = 1650, color = "#000000", describe = "Lễ bái cần dùng điểm Linh Khí."})
mapArray:push({ id = 1651, color = "#000000", describe = "Mỗi ngày được lĩnh 1 lần Linh Khí, hết hạn không lĩnh không được cộng dồn."})
mapArray:push({ id = 1652, color = "#000000", describe = "Linh Khí có thể dùng KNB mua."})
mapArray:push({ id = 1653, color = "#000000", describe = "Lễ bái nhanh sẽ tự động lễ bái 20 lần, khi không đủ Linh Khí sẽ tự động dừng."})
mapArray:push({ id = 1654, color = "#000000", describe = "Mỗi lần lễ bái nhanh đều nhấn nút lễ bái cấp cao nhất được kích hoạt hiện tại."})
mapArray:push({ id = 1655, color = "#000000", describe = "Cấp lễ bái càng cao xác suất nhận Thiên Mệnh phẩm chất cao càng lớn."})
mapArray:push({ id = 1656, color = "#000000", describe = "Thiên Mệnh bỏ không thể khảm và nuốt, nhặt sẽ nhận Linh Khí."})
mapArray:push({ id = 1657, color = "#000000", describe = "Tiêu KNB dùng Đàn Hương Lư kích hoạt nút Tế Thiên."})
mapArray:push({ id = 1658, color = "#000000", describe = "Nuốt nhanh chỉ nuốt Thiên Mệnh tím trở xuống (Không gồm tím)."})
mapArray:push({ id = 1680, color = "#000000", describe = "Đạt Lv60 mới được vào Anh Hùng Chí; "})
mapArray:push({ id = 1681, color = "#000000", describe = "Lv60 vào Anh Hùng Chí được thách đấu miễn phí 2 lần/ngày"})
mapArray:push({ id = 1682, color = "#000000", describe = "Lv60 vào Anh Hùng Chí được mua lượt thách đấu 1 lần/ngày, cấp tăng lượt mua thách đấu cũng tăng;"})
mapArray:push({ id = 1683, color = "#000000", describe = "Mỗi ải đều có giới hạn cấp, đạt cấp tương ứng cần vượt ải phía trước mới được thách đấu ải sau; "})
mapArray:push({ id = 1684, color = "#000000", describe = "00:00 hàng ngày tự động cài lại lượt thách đấu; "})
mapArray:push({ id = 1685, color = "#000000", describe = "Mỗi ải tối đa được thách đấu 7 lần/ngày"})
mapArray:push({ id = 1700, color = "#000000", describe = "Có thể luyện bất kỳ 4 kỹ năng thuần ngự của Pet Chiến."})
mapArray:push({ id = 1701, color = "#000000", describe = "Sau khi luyện cần trang bị lên lỗ kỹ năng phía trên mới có tác dụng với tướng ra trận."})
mapArray:push({ id = 1702, color = "#000000", describe = "Tỉ lệ hiệu quả phát huy của mỗi lỗ kỹ năng khác nhau, dựa theo nhu cầu để chuyển đổi tùy ý."})
mapArray:push({ id = 1710, color = "#000000", describe = "Giang Hồ Nhã Tập 00:00-21:00 mỗi CN mở."})
mapArray:push({ id = 1711, color = "#000000", describe = "Hỏi đáp có 30 câu, đáp đúng 1 câu được nhận thưởng, đáp sai không có thưởng."})
mapArray:push({ id = 1712, color = "#000000", describe = "Khi đáp đúng một số câu còn có xác suất nhận 1 phần thưởng thêm."})
mapArray:push({ id = 1713, color = "#000000", describe = "Hỏi đáp quá 1h bị coi là thất bại, không tính thành tích."})
mapArray:push({ id = 1714, color = "#000000", describe = "Hoàn thành toàn bộ hỏi đáp, dựa vào số câu đúng và xếp hạng thời gian, phát thưởng XH khi kết thúc hoạt động."})
mapArray:push({ id = 1720, color = "#000000", describe = "Đạt Lv50 trở lên mới được tham dự Phong Vân Lục;"})
mapArray:push({ id = 1721, color = "#000000", describe = "Phong Vân Lục mở 1 lần cách tuần, khi mở có thể khiêu chiến từ 10:00-22:00 thứ 3-5;"})
mapArray:push({ id = 1722, color = "#000000", describe = "Các vị đại hiệp cần dùng tướng sự kiện cung cấp cài đặt đội hình khiêu chiến;"})
mapArray:push({ id = 1723, color = "#000000", describe = "Hoạt động này chủ yếu  để so lượt ra tay ít hơn của đội hình tướng do các đại hiệp sắp xếp;"})
mapArray:push({ id = 1724, color = "#000000", describe = "Tướng trong hoạt động có thể kích hoạt duyên phận (Không hỗ trợ rối);"})
mapArray:push({ id = 1725, color = "#000000", describe = "Mỗi lần làm mới ngẫu nhiên 30 tướng, có thể chọn 5 tướng để xây dựng đội;"})
mapArray:push({ id = 1726, color = "#000000", describe = "Tướng trong đội chỉ được chọn trong số tướng làm mới trong cùng đợt;"})
mapArray:push({ id = 1727, color = "#000000", describe = "Hình thức khiêu chiến 5V5;"})
mapArray:push({ id = 1728, color = "#000000", describe = "Khi khiêu chiến sẽ tính lượt ra tay, lượt càng ít thứ hạng càng cao;"})
mapArray:push({ id = 1729, color = "#000000", describe = "Nếu lượt ra tay bằng nhau, ai phát động chiến đấu trước sẽ xếp trên;"})
mapArray:push({ id = 1730, color = "#000000", describe = "XH cá nhân trong hoạt động làm mới giao diện khiêu chiến mỗi lần vào;"})
mapArray:push({ id = 1731, color = "#000000", describe = "Sau khi kết thúc ải hiện tại, toàn bộ tướng đạt thành tích tốt nhất trong ải này sẽ không xuất hiện trong ải sau"})
mapArray:push({ id = 1732, color = "#000000", describe = "Nếu đạt được thành tích tối ưu tương đồng với các đội hình khác nhau,  ải sau dùng đội hình lần đầu, không thể làm mới đội hình"})
mapArray:push({ id = 1733, color = "#000000", describe = "Sau khi ải này kết thúc, 22:30 cùng ngày sẽ làm mới BXH tương ứng;"})
mapArray:push({ id = 1734, color = "#000000", describe = "Sau khi ải này kết thúc, 0h ngày thứ 2 phát thưởng tương ứng (qua thư);"})
mapArray:push({ id = 1735, color = "#000000", describe = "Vào 0h ngày thứ 2 nhấp đội hình lịch sử ải tương ứng để xem đội hình tối ưu của bản thân;"})
mapArray:push({ id = 1736, color = "#000000", describe = "BXH tổng lấy tổng số lượt ra tay của 3 ải, nếu tổng số lượt tương đồng, người phát động chiến đấu ải cuối trước sẽ xếp trước;"})
mapArray:push({ id = 1737, color = "#000000", describe = "Thưởng BXH tổng sẽ phát vào 0h thứ 6 sau khi kết thúc sự kiện;"})
mapArray:push({ id = 1738, color = "#000000", describe = "Sau khi kết thúc sự kiện sẽ bảo lưu dữ liệu hoạt động lần này để người chơi tra cứu, cho tới khi mở sự kiện lần sau;"})
return mapArray
