local mapArray = MEMapArray:new()
mapArray:push({ id = 1, attribute = "3_770|5_770", immune_rate = "", effect_active = "", effect_passive = "", name = "2 vị trí trợ chiến Ăn Ý +1", power = 0, des = "Tất cả tướng ra trận Thân Pháp +7700 Thủ +7700"})
mapArray:push({ id = 2, attribute = "2_770|4_770", immune_rate = "", effect_active = "", effect_passive = "", name = "3 vị trí trợ chiến Ăn Ý +2", power = 0, des = "Tất cả tướng ra trận Võ lực +7700 Nội lực +7700"})
mapArray:push({ id = 3, attribute = "1_1160", immune_rate = "", effect_active = "", effect_passive = "", name = "4 vị trí trợ chiến Ăn Ý +3", power = 0, des = "Tất cả tướng ra trận HP +11600"})
mapArray:push({ id = 4, attribute = "18_600", immune_rate = "", effect_active = "", effect_passive = "", name = "5 vị trí trợ chiến Ăn Ý +4", power = 0, des = "Tất cả tướng ra trận HP +60%"})
mapArray:push({ id = 5, attribute = "19_400|21_400", immune_rate = "", effect_active = "", effect_passive = "", name = "6 vị trí trợ chiến Ăn Ý +5", power = 0, des = "Tất cả tướng ra trận Võ Lực +40% Nội Lực +40%"})
mapArray:push({ id = 6, attribute = "", immune_rate = "", effect_active = "", effect_passive = "45_50", name = "6 vị trí trợ chiến Ăn Ý +6", power = 5000, des = "Tất cả tướng ra trận nhận trị liệu +5%"})
mapArray:push({ id = 7, attribute = "", immune_rate = "", effect_active = "", effect_passive = "44_-800", name = "6 vị trí trợ chiến Ăn Ý +7", power = 8000, des = "S.thương tất cả tướng ra trận phải chịu -8%"})
mapArray:push({ id = 8, attribute = "", immune_rate = "", effect_active = "44_100", effect_passive = "", name = "6 vị trí trợ chiến Ăn Ý +8", power = 10000, des = "S.thương tất cả tướng ra trận +10%"})
mapArray:push({ id = 9, attribute = "15_900", immune_rate = "", effect_active = "", effect_passive = "", name = "6 vị trí trợ chiến Ăn Ý +9", power = 0, des = "Né tất cả tướng ra trận +9000"})
mapArray:push({ id = 10, attribute = "18_200|20_200", immune_rate = "", effect_active = "", effect_passive = "", name = "6 vị trí trợ chiến Ăn Ý +10", power = 0, des = "Tất cả tướng ra trận HP +20% Thủ +20%"})
mapArray:push({ id = 11, attribute = "16_100", immune_rate = "", effect_active = "", effect_passive = "", name = "6 vị trí trợ chiến Ăn Ý +11", power = 0, des = "Tất cả tướng ra trận bạo kích +10%"})
mapArray:push({ id = 12, attribute = "", immune_rate = "", effect_active = "44_120", effect_passive = "", name = "6 vị trí trợ chiến Ăn Ý +12", power = 20000, des = "Tất cả tướng ra trận s.thương +12%"})
return mapArray