local mapArray = MEMapArray:new()
mapArray:push({ id = 1, quality = 1, sub_count = 2, sub_type = 1, tppe_value = 0, describe_title = "宝石孔：+1"})
mapArray:push({ id = 2, quality = 2, sub_count = 3, sub_type = 3, tppe_value = 100, describe_title = "附加属性提升：1%"})
mapArray:push({ id = 3, quality = 3, sub_count = 3, sub_type = 3, tppe_value = 300, describe_title = "附加属性提升：3%"})
mapArray:push({ id = 5, quality = 3, sub_count = 2, sub_type = 3, tppe_value = 200, describe_title = "附加属性提升：2%"})
mapArray:push({ id = 4, quality = 4, sub_count = 5, sub_type = 2, tppe_value = 0, describe_title = "属性条数：+1"})
mapArray:push({ id = 6, quality = 4, sub_count = 1, sub_type = 3, tppe_value = 400, describe_title = "附加属性提升：4%"})
mapArray:push({ id = 7, quality = 4, sub_count = 2, sub_type = 3, tppe_value = 500, describe_title = "附加属性提升：5%"})
mapArray:push({ id = 8, quality = 4, sub_count = 3, sub_type = 3, tppe_value = 600, describe_title = "附加属性提升：6%"})
mapArray:push({ id = 9, quality = 4, sub_count = 4, sub_type = 3, tppe_value = 700, describe_title = "附加属性提升：7%"})
mapArray:push({ id = 10, quality = 5, sub_count = 3, sub_type = 3, tppe_value = 800, describe_title = "附加属性提升：8%"})
mapArray:push({ id = 11, quality = 5, sub_count = 4, sub_type = 3, tppe_value = 900, describe_title = "附加属性提升：9%"})
mapArray:push({ id = 12, quality = 5, sub_count = 5, sub_type = 3, tppe_value = 1000, describe_title = "附加属性提升：10%"})
mapArray:push({ id = 13, quality = 6, sub_count = 3, sub_type = 3, tppe_value = 1150, describe_title = "附加属性提升：11%"})
mapArray:push({ id = 14, quality = 6, sub_count = 4, sub_type = 3, tppe_value = 1300, describe_title = "附加属性提升：13%"})
mapArray:push({ id = 15, quality = 6, sub_count = 5, sub_type = 3, tppe_value = 1500, describe_title = "附加属性提升：15%"})
mapArray:push({ id = 16, quality = 7, sub_count = 3, sub_type = 3, tppe_value = 1800, describe_title = "附加属性提升：18%"})
mapArray:push({ id = 17, quality = 7, sub_count = 4, sub_type = 3, tppe_value = 2100, describe_title = "附加属性提升：21%"})
mapArray:push({ id = 18, quality = 7, sub_count = 5, sub_type = 3, tppe_value = 2400, describe_title = "附加属性提升：24%"})
mapArray:push({ id = 19, quality = 8, sub_count = 3, sub_type = 3, tppe_value = 2800, describe_title = "附加属性提升：28%"})
mapArray:push({ id = 20, quality = 8, sub_count = 4, sub_type = 3, tppe_value = 3200, describe_title = "附加属性提升：32%"})
mapArray:push({ id = 21, quality = 8, sub_count = 5, sub_type = 3, tppe_value = 3600, describe_title = "附加属性提升：36%"})
return mapArray